"""
utils/ipo_en_data.py
English I/P/O content for BESS skill modules.
Used by 07_IPO_Checklists.py when lang == 'EN'.
Key = skill filename (without .md), Value = dict with 'inputs', 'processes', 'outputs' lists.
"""

EN_IPO: dict[str, dict[str, list[str]]] = {

    "bess-project-manager": {
        "inputs": [
            "Project specs (MW/MWh, EPC/EPCM contract type)",
            "Schedule (NTP, PAC, FAC dates) & LD conditions",
            "Budget & financial close conditions",
            "Owner's requirements & approval procedures",
            "WBS baseline & stakeholder register",
            "Existing Lessons Learned database",
        ],
        "processes": [
            "Develop Project Execution Plan (PEP) & Project Charter",
            "Establish WBS (Level 3–4) & RACI matrix",
            "Conduct kick-off meeting & set reporting cadence",
            "Update Weekly & Monthly progress reports",
            "Track SPI / CPI via EVM & S-Curve",
            "Manage Change (MOC) — log Variation Orders",
            "Resolve engineering / procurement / site interfaces",
            "Monitor Risk Register & trigger mitigation actions",
            "Prepare PAC / FAC documentation & punch-list closeout",
        ],
        "outputs": [
            "Project Execution Plan (PEP) (.docx)",
            "Weekly Progress Report (.docx/.pptx)",
            "Monthly Management Report (.pptx)",
            "RACI Matrix (.xlsx)",
            "MOC / Change Log (.xlsx)",
            "Lessons Learned Report (.docx)",
            "Project Close-out Report (.docx)",
        ],
    },

    "bess-scheduler": {
        "inputs": [
            "Project scope (MW/MWh) & target market",
            "Contractual milestones: NTP / PAC / FAC & LD basis",
            "Equipment lead times: Battery / PCS / Transformer",
            "Permit schedule (construction, fire, grid interconnection)",
            "Site construction constraints (weather, access)",
            "Commissioning duration plan",
        ],
        "processes": [
            "Build WBS (7-level) and activity network (FS/FF/SS/SF)",
            "Identify Critical Path and Near-Critical (Float ≤ 5 days)",
            "Set Baseline Schedule in P6 / MS Project",
            "Run 3-week Look-Ahead schedule weekly",
            "Calculate SPI / CPI from earned value data",
            "Plot S-Curve: PV vs EV vs AC",
            "Conduct Delay Analysis (Window / TIA method) on delays",
            "Perform Monte Carlo simulation for P50/P80/P90 completion dates",
            "Issue delay notice & recovery plan to Owner",
        ],
        "outputs": [
            "Baseline Schedule (.xer / .mpp / PDF Gantt)",
            "Weekly Progress Report with S-Curve",
            "3-Week Look-Ahead (Excel)",
            "Delay Analysis Report (.docx)",
            "Monte Carlo Risk Schedule (P50/P80/P90)",
            "Recovery Schedule",
        ],
    },

    "bess-risk-manager": {
        "inputs": [
            "Project scope (MW/MWh) & contract type (FIDIC EPC)",
            "Baseline schedule & cost budget",
            "Target market (KR/US/JP/AU/UK/EU/RO)",
            "Vendor financial assessment & lead time data",
            "Grid interconnection approval timeline",
            "Exchange rate & commodity price data",
        ],
        "processes": [
            "Identify risks using Risk Breakdown Structure (RBS)",
            "Score each risk: P (1–5) × I (1–5) → Risk Score",
            "Grade risks: Critical ≥ 20 / High 12–16 / Medium 5–10 / Low 1–4",
            "Define response strategy: Avoid / Mitigate / Transfer / Accept",
            "Assign risk Owner and response deadline",
            "Update Risk Register weekly; escalate Critical risks to PM",
            "Run Monte Carlo cost risk simulation (N=10,000)",
            "Monitor Early Warning Indicators (SPI < 0.9, CPI < 0.95)",
            "Issue Monthly Risk Report to Owner",
        ],
        "outputs": [
            "Risk Register (.xlsx) — ID, IF-THEN description, P, I, Score, Response",
            "Quantitative Risk Analysis (Monte Carlo P50/P80/P90)",
            "Monthly Risk Report (.docx/.pptx)",
            "Risk Heatmap (5×5)",
            "Early Warning Dashboard",
            "Contingency Usage Log (.xlsx)",
        ],
    },

    "bess-system-engineer": {
        "inputs": [
            "RFP / Client specifications (MW, MWh, grid voltage)",
            "Target market & grid code requirements",
            "C-Rate requirement (0.25C / 0.5C / 1C / 2C)",
            "Site environmental data (temperature, altitude)",
            "Battery chemistry preference (LFP / NMC)",
            "RTE, auxiliary loss, and EPC margin targets",
        ],
        "processes": [
            "Calculate total energy & power scaling (nameplate DC capacity)",
            "Account for RTE, auxiliary loads, and degradation margin",
            "Determine number of battery enclosures & PCS skids",
            "Draft Single Line Diagram (SLD) concept",
            "Select key equipment ratings (PCS, Transformer, MV switchgear)",
            "Coordinate footprint with E-BOP & C-BOP teams",
            "Review regional standards (IEEE 1547, KEC, IEC 62619, etc.)",
        ],
        "outputs": [
            "BESS Conceptual Architecture Diagram",
            "System Sizing Calculation Sheet (.xlsx)",
            "High-level Equipment Schedule / BOM",
            "SLD Base Concept Drawing",
            "System Architecture Report (.txt / .docx)",
        ],
    },

    "bess-ebop-engineer": {
        "inputs": [
            "BESS capacity (MW / MWh) & grid voltage",
            "Grid code & protection relay requirements",
            "Cable routing distances & load currents",
            "Soil resistivity data for grounding design",
            "Target market standards (NEC, KEC, IEC 60364, AS/NZS)",
        ],
        "processes": [
            "Size main & PCS transformers (MVA, impedance, vector group)",
            "Calculate MV/LV cable cross-sections (thermal & voltage drop)",
            "Design protection relay coordination (OVR/UVR, ROCOF, OCEF)",
            "Design grounding grid to IEEE 80 / IEC 60364 standards",
            "Verify arc flash hazard & PPE category",
            "Produce Single Line Diagram (SLD) — IFA / IFC revisions",
            "Review regional E-BOP standards compliance",
        ],
        "outputs": [
            "Transformer Sizing Calculation (.xlsx)",
            "Cable Sizing Schedule (.xlsx)",
            "Protection Relay Setting Sheets (.xlsx)",
            "Grounding Grid Design Calculation",
            "SLD — Issued for Approval (IFA) / Issued for Construction (IFC)",
            "E-BOP Design Report (.docx)",
        ],
    },

    "bess-cbop-engineer": {
        "inputs": [
            "Number and dimensions of battery enclosures & PCS skids",
            "Equipment weights & operating loads",
            "Soil bearing capacity & geotechnical report",
            "Design wind speed & seismic zone",
            "Target market civil standards (IBC/ASCE 7, KDS, Eurocode)",
        ],
        "processes": [
            "Design equipment foundation pads (sizing, rebar, concrete grade)",
            "Calculate pad bearing pressure vs soil capacity",
            "Design cable trench & duct bank routing",
            "Specify HVAC system for enclosures & MV rooms",
            "Design fire protection system layout (suppression, separation)",
            "Verify NFPA 855 / local fire code separation distances",
            "Prepare civil grading & drainage plan",
        ],
        "outputs": [
            "Foundation Pad Design Calculation (.xlsx)",
            "Trench & Duct Bank Layout Drawing",
            "Civil Grading & Drainage Plan",
            "HVAC Equipment Specification",
            "Fire Protection Layout Drawing",
            "C-BOP Design Report (.docx)",
        ],
    },

    "bess-battery-expert": {
        "inputs": [
            "Target capacity (MW / MWh) & C-Rate",
            "Battery chemistry selection (LFP / NMC / Solid-State)",
            "Cycle life requirement & calendar life",
            "Operating temperature range",
            "BMS & thermal management preferences",
        ],
        "processes": [
            "Define cell / module / rack / system hierarchy",
            "Calculate number of cells in series & parallel",
            "Size BMS parameters (SOC window, SOH tracking)",
            "Analyse thermal management: liquid vs air cooling",
            "Review cycle life degradation model (capacity fade curve)",
            "Evaluate LFP vs NMC trade-off for application",
            "Review IEC 62619 / UL 9540 safety certification requirements",
        ],
        "outputs": [
            "Battery System Architecture Design (.docx)",
            "Cell-to-System Sizing Calculation (.xlsx)",
            "Degradation Projection Report (SOH vs EFC)",
            "BMS Parameter Setting Sheet",
            "Safety Certification Requirement Checklist",
        ],
    },

    "bess-data-analyst": {
        "inputs": [
            "Real-time SCADA data (SOC, voltage, current, temperature)",
            "Historical charge/discharge cycle data",
            "Grid metering data (every 5 / 15 min)",
            "Manufacturer SOH degradation curve",
            "Target RTE & auxiliary loss targets",
        ],
        "processes": [
            "Calculate system availability & MTBF",
            "Track Round-Trip Efficiency (RTE) trend vs target",
            "Plot SOH vs EFC degradation curve",
            "Run Isolation Forest anomaly detection on cell temperatures",
            "Build monthly Charge / Discharge profile charts",
            "Generate KPI dashboard (availability, RTE, aux power)",
            "Alert on Early Warning Indicators (T > 35°C, ΔV > 50 mV)",
        ],
        "outputs": [
            "Monthly KPI Dashboard Report (.pptx)",
            "SOH Degradation Trend Chart",
            "Anomaly Detection Alert Log",
            "Efficiency Loss Analysis Report",
            "Data Reporting Package to grid operator",
        ],
    },

    "bess-fire-engineer": {
        "inputs": [
            "BESS capacity & enclosure layout plan",
            "Battery chemistry (LFP / NMC) & thermal runaway data",
            "Building category & occupancy classification",
            "Target market fire codes (NFPA 855, KFS, AS 5139)",
            "Site environmental data (wind direction, slope)",
        ],
        "processes": [
            "Calculate minimum separation distances (NFPA 855 / local code)",
            "Select fire suppression system (clean agent, water mist, CO₂)",
            "Design smoke extraction system & FDS simulation",
            "Specify thermal runaway detection (rack-level BMS + thermal camera)",
            "Review sprinkler system layout vs NFPA 13",
            "Prepare Emergency Response Plan (ERP)",
            "Coordinate authority having jurisdiction (AHJ) review",
        ],
        "outputs": [
            "Fire Protection Design Report (.docx)",
            "Equipment Separation Distance Calculation",
            "Fire Suppression System Specification",
            "Smoke Extraction & FDS Analysis Report",
            "Emergency Response Plan (ERP) (.docx)",
            "AHJ Submission Package",
        ],
    },

    "bess-procurement-expert": {
        "inputs": [
            "Project BOM (Battery, PCS, Transformer, Switchgear, Cable)",
            "Project schedule — required delivery dates by package",
            "Budget & contract form (Turnkey / Supply-only / FIDIC)",
            "Approved vendor list (AVL) & qualification status",
            "Target market import/export regulations",
        ],
        "processes": [
            "Issue RFQ packages to qualified vendors",
            "Evaluate bids: Technical + Commercial + Schedule",
            "Negotiate terms: price, payment, warranty, LD, delivery",
            "Place Purchase Orders and track acknowledgements",
            "Monitor vendor manufacturing progress (MFR reports)",
            "Witness Factory Acceptance Tests (FAT)",
            "Coordinate logistics: sea freight, customs, site delivery",
            "Process vendor invoices vs milestone payment schedule",
        ],
        "outputs": [
            "RFQ Package (Technical Specification + Commercial Terms)",
            "Bid Evaluation Matrix (.xlsx)",
            "Purchase Order (PO) set",
            "Procurement Status Report (PSR) (.xlsx)",
            "FAT Acceptance Certificate",
            "Packing List & Shipping Documents",
        ],
    },

    "bess-financial-analysis": {
        "inputs": [
            "Project CAPEX estimate by package (Battery, EPC, Grid)",
            "Revenue model: market (ERCOT/AEMO), tariff, PPA",
            "Financing structure: equity ratio, loan terms, interest rate",
            "Target IRR / NPV / DSCR thresholds",
            "Battery degradation profile & replacement cost",
            "O&M cost projection ($/MWh-yr)",
        ],
        "processes": [
            "Build 20-year cash flow model in Excel",
            "Calculate project IRR, NPV, Payback Period",
            "Compute DSCR (Debt Service Coverage Ratio) year-by-year",
            "Run sensitivity analysis on CAPEX ±10%, revenue ±15%",
            "Perform scenario analysis: Base / Bull / Bear",
            "Assess IRA tax credit (US) or government incentive eligibility",
            "Prepare financial model for lender / investor review",
        ],
        "outputs": [
            "Financial Model (.xlsx) — 20-year DCF, IRR, NPV, DSCR",
            "Sensitivity Analysis Charts",
            "Investment Memo (.docx)",
            "Lender's Information Memorandum (LIM)",
            "Incentive Eligibility Assessment Report",
        ],
    },

    "bess-structural-analyst": {
        "inputs": [
            "Equipment weights & center of gravity data",
            "Foundation pad dimensions & soil report",
            "Seismic zone & design acceleration (g)",
            "Wind load (design wind speed, m/s)",
            "Snow load (if applicable)",
            "Applicable structural code (ASCE 7, KDS 41, Eurocode 8)",
        ],
        "processes": [
            "Calculate dead, live, wind, and seismic loads per code",
            "Determine governing load combination (1.2D + 1.6L, etc.)",
            "Calculate DCR (Demand / Capacity Ratio) for foundation",
            "Design rebar layout & concrete grade",
            "Perform Von Mises stress analysis for steel frames",
            "Verify anchor bolt capacity against seismic uplift",
            "Check settlement & differential settlement criteria",
        ],
        "outputs": [
            "Structural Calculation Package (.xlsx / .pdf)",
            "Foundation Plan & Detail Drawings",
            "Anchor Bolt Schedule",
            "DCR Summary Table",
            "Structural Analysis Report (.docx)",
        ],
    },

    "bess-qaqc-engineer": {
        "inputs": [
            "Project QA/QC Plan (PQP) & Inspection Test Plan (ITP)",
            "Vendor drawing & datasheet submittals",
            "Factory Acceptance Test (FAT) witness plan",
            "Site Acceptance Test (SAT) procedures",
            "Non-Conformance Report (NCR) register",
        ],
        "processes": [
            "Review & approve vendor submittals (drawings, datasheets, CoC)",
            "Attend FAT at vendor factory — witness key tests",
            "Conduct incoming inspection at site",
            "Perform in-process construction inspection (ITP hold points)",
            "Issue NCRs for non-conformances; track Corrective Action Reports (CAR)",
            "Conduct Pre-Commissioning checks (insulation, continuity, relay)",
            "Complete punch-list & handover to commissioning team",
        ],
        "outputs": [
            "Inspection & Test Plan (ITP)",
            "FAT Witness Report",
            "Incoming Inspection Records",
            "NCR / CAR Log (.xlsx)",
            "Pre-Commissioning Checksheets",
            "Quality Close-out Report (.docx)",
        ],
    },

    "bess-contract-specialist": {
        "inputs": [
            "Contract documents (FIDIC Silver/Gold, NEC, bespoke EPC)",
            "Project schedule (Baseline) & milestone dates",
            "Change event notifications from site or Owner",
            "Variation Order (VO) requests",
            "Dispute records & correspondence log",
        ],
        "processes": [
            "Review contract risk allocation: LD, performance guarantees, indemnities",
            "Track contract milestones & notice periods (FIDIC Clause 20)",
            "Draft & submit Extension of Time (EOT) claims",
            "Prepare Additional Cost claims with substantiation",
            "Manage Variation Orders (VO) — scope, price, time impact",
            "Maintain contemporaneous records for potential disputes",
            "Negotiate settlement agreements with Owner",
        ],
        "outputs": [
            "Contract Risk Register (.xlsx)",
            "EOT Claim Submission (.docx)",
            "Additional Cost Claim Report",
            "Variation Order Log (.xlsx)",
            "Contract Correspondence Log",
            "Settlement Agreement Draft (.docx)",
        ],
    },

    "bess-grid-interconnection": {
        "inputs": [
            "BESS capacity (MW / MWh) & point of interconnection voltage",
            "Grid operator (KEPCO / ERCOT / AEMO / National Grid) requirements",
            "Grid code technical requirements (FRT, reactive power, ROCOF)",
            "Utility interconnection application forms & fees",
            "Power system study report from grid operator",
        ],
        "processes": [
            "Submit grid interconnection application to utility",
            "Provide technical data sheet (TDS) for PCS & BESS",
            "Respond to power system study reports (short circuit, load flow)",
            "Negotiate interconnection agreement commercial terms",
            "Confirm protection relay settings with utility",
            "Conduct grid interconnection test (VRT, FFR, ROCOF test)",
            "Obtain grid interconnection approval certificate",
        ],
        "outputs": [
            "Grid Interconnection Application Package",
            "Technical Data Sheet (TDS) for PCS & BESS",
            "Power System Study Review Comments",
            "Interconnection Agreement (IA)",
            "Protection Relay Setting Confirmation",
            "Grid Interconnection Test Report",
            "Approval Certificate from Utility",
        ],
    },

    # ── 47 additional BESS EPC skill entries ──────────────────────────

    "bess-aiml-engineer": {
        "inputs": [
            "Historical SCADA data (SOC, voltage, current, temperature)",
            "Battery degradation logs & cycle data",
            "Weather forecast API data (irradiance, temperature, wind)",
            "Market price signals (LMP, ancillary service prices)",
            "ML framework & model registry requirements",
            "Feature engineering specification document",
        ],
        "processes": [
            "Collect and clean time-series data from SCADA/EMS",
            "Perform exploratory data analysis (EDA) & feature engineering",
            "Train SOH prediction model (LSTM / XGBoost / Random Forest)",
            "Develop anomaly detection model for cell-level faults",
            "Build energy dispatch optimization model (RL / MILP)",
            "Validate model accuracy (RMSE, MAE, F1 score) on test set",
            "Deploy model to production via MLOps pipeline (MLflow / Kubeflow)",
            "Monitor model drift & trigger retraining schedule",
        ],
        "outputs": [
            "ML Model Performance Report (.docx/.pdf)",
            "SOH Prediction Dashboard (web app)",
            "Anomaly Detection Alert System specification",
            "Trained Model Artifacts & API endpoint documentation",
            "Model Validation Report with accuracy metrics (.xlsx)",
        ],
    },

    "bess-cable-engineer": {
        "inputs": [
            "Single Line Diagram (SLD) & load schedule",
            "Cable routing distances (DC, MV, LV, control)",
            "Ambient temperature & soil thermal resistivity",
            "Short-circuit current levels at each bus",
            "Applicable cable standards (IEC 60502, NEC Article 310, AS/NZS 3008)",
        ],
        "processes": [
            "Calculate cable current-carrying capacity with derating factors",
            "Verify voltage drop ≤ allowable limit (3% MV, 5% LV typical)",
            "Check short-circuit withstand rating (I²t) per cable size",
            "Select cable type (XLPE, EPR) & insulation voltage class",
            "Design cable tray fill ratio & routing layout",
            "Prepare cable pull tension calculations for long runs",
            "Coordinate cable schedule with procurement & construction",
        ],
        "outputs": [
            "Cable Sizing Calculation Sheet (.xlsx)",
            "Cable Schedule with tag, from/to, size, length (.xlsx)",
            "Cable Routing Layout Drawing (.dwg/.pdf)",
            "Cable Pull Tension Calculation (.xlsx)",
            "Cable Specification & Datasheet (.docx)",
        ],
    },

    "bess-cfd-analyst": {
        "inputs": [
            "Battery enclosure geometry (3D CAD model)",
            "Heat generation rates per module/rack (W)",
            "HVAC system airflow / coolant flow specifications",
            "Ambient temperature range & solar radiation data",
            "Thermal runaway propagation scenario parameters",
        ],
        "processes": [
            "Build 3D mesh of enclosure & battery rack geometry",
            "Define boundary conditions (inlet temp, flow rate, heat flux)",
            "Run steady-state CFD simulation for normal operation",
            "Run transient CFD simulation for thermal runaway propagation",
            "Analyze temperature distribution & hot-spot identification",
            "Optimize HVAC duct placement & airflow distribution",
            "Validate CFD results against manufacturer thermal test data",
            "Perform sensitivity analysis on ambient temperature extremes",
        ],
        "outputs": [
            "CFD Simulation Report with temperature contour plots (.pdf)",
            "Hot-Spot Analysis & Mitigation Recommendations (.docx)",
            "HVAC Optimization Report (.docx)",
            "Thermal Runaway Propagation Analysis (.pdf)",
            "Airflow Distribution Visualization (3D renderings)",
        ],
    },

    "bess-circuit-breaker-expert": {
        "inputs": [
            "Single Line Diagram (SLD) & bus ratings",
            "Short-circuit study results (symmetrical & asymmetrical kA)",
            "Load current & overload requirements per feeder",
            "Protection coordination time-current curves (TCC)",
            "Applicable standards (IEC 62271, IEEE C37, ANSI)",
        ],
        "processes": [
            "Select circuit breaker type (VCB, SF6, ACB, MCCB) per voltage level",
            "Verify breaking capacity ≥ prospective fault current",
            "Coordinate breaker trip curves with upstream/downstream devices",
            "Specify breaker accessories (shunt trip, UVR, motorized mechanism)",
            "Review arc flash incident energy & breaker clearing time",
            "Prepare breaker setting schedule for protection engineer",
            "Coordinate FAT witness points for breaker testing",
        ],
        "outputs": [
            "Circuit Breaker Selection Schedule (.xlsx)",
            "Time-Current Coordination Study (.pdf)",
            "Breaker Setting Schedule (.xlsx)",
            "Arc Flash Hazard Calculation per breaker location (.xlsx)",
            "Circuit Breaker Datasheet & Specification (.docx)",
        ],
    },

    "bess-commissioning-coordinator": {
        "inputs": [
            "Commissioning plan & schedule from EPC contractor",
            "Pre-commissioning checksheets (completed)",
            "Equipment O&M manuals & vendor commissioning procedures",
            "Grid operator interconnection test requirements",
            "Owner's performance acceptance criteria (PAC)",
            "Punch-list from construction / QA/QC team",
        ],
        "processes": [
            "Develop detailed commissioning execution plan & sequence",
            "Verify completion of all pre-commissioning activities",
            "Coordinate vendor representatives for on-site commissioning",
            "Execute equipment energization sequence (transformer → MV → PCS → battery)",
            "Perform functional tests (charge/discharge, protection trip, BMS comms)",
            "Conduct performance guarantee test (capacity, RTE, response time)",
            "Resolve punch-list items & obtain Owner sign-off",
            "Coordinate grid compliance tests with utility witness",
            "Prepare PAC documentation package",
        ],
        "outputs": [
            "Commissioning Execution Plan (.docx)",
            "Equipment Energization Checklist (.xlsx)",
            "Functional Test Reports (.docx/.pdf)",
            "Performance Guarantee Test Report (.docx)",
            "PAC Certificate & Punch-list Closeout (.xlsx)",
            "Grid Compliance Test Report (.pdf)",
        ],
    },

    "bess-cost-analyst": {
        "inputs": [
            "Project scope & capacity (MW/MWh)",
            "Equipment vendor quotations & BOM",
            "Construction labor rates & productivity data",
            "Historical cost database from similar BESS projects",
            "EPC contract price breakdown structure",
            "Foreign exchange rates & escalation indices",
        ],
        "processes": [
            "Develop CAPEX estimate by work package (battery, PCS, BOP, EPC)",
            "Build cost breakdown structure (CBS) aligned with WBS",
            "Calculate $/kWh and $/kW benchmarks vs industry data",
            "Track committed cost vs budget (CPI analysis)",
            "Forecast Estimate at Completion (EAC) monthly",
            "Analyze change order cost impact & contingency drawdown",
            "Prepare cost-to-complete projection for lender reporting",
        ],
        "outputs": [
            "CAPEX Estimate Report (.xlsx)",
            "Cost Breakdown Structure (CBS) (.xlsx)",
            "Monthly Cost Report with EAC forecast (.xlsx/.pptx)",
            "Change Order Cost Impact Analysis (.xlsx)",
            "Contingency Drawdown Log (.xlsx)",
            "Benchmark Cost Analysis ($/kWh, $/kW) (.docx)",
        ],
    },

    "bess-emc-analyst": {
        "inputs": [
            "Equipment layout & cable routing drawings",
            "PCS switching frequency & harmonic spectrum data",
            "EMC standards (IEC 61000 series, FCC Part 15, CISPR 11)",
            "Sensitive equipment locations (BMS, SCADA, protection relays)",
            "Grounding & shielding design documents",
        ],
        "processes": [
            "Identify EMI sources (PCS inverter, DC-DC converter, switchgear)",
            "Analyze conducted & radiated emission levels vs limits",
            "Design EMC mitigation: cable segregation, shielding, filtering",
            "Specify EMC filters for PCS AC/DC terminals",
            "Review grounding topology for EMC (single-point vs mesh)",
            "Coordinate EMC pre-compliance testing plan",
            "Verify immunity levels of BMS & SCADA equipment",
        ],
        "outputs": [
            "EMC Assessment Report (.docx)",
            "Cable Segregation & Routing Guideline (.docx)",
            "EMC Filter Specification Sheet (.xlsx)",
            "EMC Test Plan (.docx)",
            "EMC Compliance Certificate / Declaration of Conformity",
        ],
    },

    "bess-env-engineer": {
        "inputs": [
            "Project site location & land use zoning",
            "Environmental Impact Assessment (EIA) requirements",
            "Noise emission data from equipment vendors",
            "Hazardous material inventory (electrolyte, coolant)",
            "Local environmental regulations & permit requirements",
            "Flora/fauna survey data & heritage site records",
        ],
        "processes": [
            "Conduct Environmental Impact Assessment (EIA) screening",
            "Perform noise impact assessment & modeling",
            "Prepare spill prevention & containment plan",
            "Develop waste management plan (battery end-of-life recycling)",
            "Obtain environmental permits (air, water, waste)",
            "Design stormwater management & erosion control plan",
            "Monitor construction-phase environmental compliance",
            "Prepare Environmental Management Plan (EMP)",
        ],
        "outputs": [
            "Environmental Impact Assessment Report (.docx/.pdf)",
            "Noise Impact Assessment Report (.docx)",
            "Environmental Management Plan (EMP) (.docx)",
            "Spill Prevention & Containment Plan (.docx)",
            "Environmental Permit Application Package",
            "Waste Management Plan (.docx)",
        ],
    },

    "bess-facility-manager": {
        "inputs": [
            "As-built drawings & O&M manuals",
            "Equipment warranty terms & service contracts",
            "Spare parts inventory list",
            "Site access & security procedures",
            "Preventive maintenance schedule from OEM",
        ],
        "processes": [
            "Establish facility operations procedures & SOPs",
            "Implement CMMS (Computerized Maintenance Management System)",
            "Schedule preventive maintenance per OEM recommendations",
            "Manage spare parts inventory & reorder points",
            "Monitor facility security (CCTV, access control, fencing)",
            "Coordinate emergency response drills & safety training",
            "Track utility consumption & facility operating costs",
            "Manage site landscaping, drainage, & road maintenance",
        ],
        "outputs": [
            "Facility Operations Manual (.docx)",
            "Preventive Maintenance Schedule (.xlsx)",
            "Spare Parts Inventory Report (.xlsx)",
            "CMMS Work Order Reports (.pdf)",
            "Facility Operating Cost Report (.xlsx)",
            "Emergency Response Drill Records (.docx)",
        ],
    },

    "bess-fit-procedure": {
        "inputs": [
            "BESS system architecture & SLD",
            "PCS & BMS communication protocol specifications",
            "Grid code compliance test requirements",
            "Owner's performance acceptance criteria",
            "Equipment FAT reports & commissioning prerequisites",
            "SCADA/EMS integration specification",
        ],
        "processes": [
            "Develop Factory Integration Test (FIT) procedure & test script",
            "Define pass/fail criteria for each test case",
            "Verify BMS-PCS-SCADA communication loop (Modbus/DNP3/IEC 61850)",
            "Test charge/discharge control sequences & interlocks",
            "Validate protection function activation (over-voltage, over-current, over-temperature)",
            "Conduct Site Integration Test (SIT) after installation",
            "Test grid-forming / grid-following mode switching",
            "Document all test results & deviations",
        ],
        "outputs": [
            "FIT Procedure Document (.docx)",
            "FIT/SIT Test Protocol with pass/fail checklist (.xlsx)",
            "Communication Loop Test Report (.docx)",
            "Protection Function Test Report (.docx)",
            "Integration Test Summary Report (.docx/.pdf)",
            "Deviation & Corrective Action Log (.xlsx)",
        ],
    },

    "bess-grounding-engineer": {
        "inputs": [
            "Site soil resistivity survey data (Wenner method)",
            "Equipment layout & foundation plan",
            "Fault current levels (single-line-to-ground, three-phase)",
            "Touch & step voltage safety criteria",
            "Applicable grounding standards (IEEE 80, IEC 60364, AS/NZS 3000)",
        ],
        "processes": [
            "Model soil resistivity (two-layer model)",
            "Design grounding grid geometry (conductor spacing, depth, material)",
            "Calculate ground resistance target (< 1 Ω typical for substations)",
            "Compute touch & step voltage and compare to tolerable limits",
            "Specify ground rods, ground conductors, & exothermic weld joints",
            "Coordinate lightning protection system with grounding grid",
            "Verify grounding continuity test procedure for construction",
        ],
        "outputs": [
            "Grounding Grid Design Calculation (.xlsx)",
            "Grounding Layout Drawing (.dwg/.pdf)",
            "Touch & Step Voltage Analysis Report (.docx)",
            "Ground Resistance Test Procedure (.docx)",
            "Lightning Protection System Design (.docx)",
            "Grounding Material Specification & BOM (.xlsx)",
        ],
    },

    "bess-hr-manager": {
        "inputs": [
            "Project organization chart & staffing plan",
            "Labor market data for target project location",
            "Employment regulations (local labor law, work permits)",
            "Training & competency requirements per role",
            "Company HR policies & compensation guidelines",
        ],
        "processes": [
            "Develop project staffing plan & mobilization schedule",
            "Recruit engineers, technicians, and site personnel",
            "Process work permits & visa applications for overseas projects",
            "Coordinate onboarding & safety induction training",
            "Manage payroll, benefits, and time-tracking",
            "Monitor labor productivity & workforce utilization",
            "Handle employee relations, grievances, and demobilization",
        ],
        "outputs": [
            "Project Staffing Plan (.xlsx)",
            "Mobilization / Demobilization Schedule (.xlsx)",
            "Training Records & Competency Matrix (.xlsx)",
            "Monthly Manpower Report (.xlsx/.pptx)",
            "Work Permit & Visa Tracker (.xlsx)",
        ],
    },

    "bess-hybrid-specialist": {
        "inputs": [
            "Solar PV / Wind farm capacity & generation profile",
            "BESS capacity (MW/MWh) & dispatch requirements",
            "Grid connection capacity & curtailment constraints",
            "Site solar irradiance & wind resource data",
            "Hybrid plant controller (HPC) requirements",
            "Revenue model for co-located hybrid plant",
        ],
        "processes": [
            "Size BESS capacity relative to renewable generation profile",
            "Design hybrid plant controller (HPC) dispatch logic",
            "Optimize charge/discharge strategy to minimize curtailment",
            "Model energy yield with BESS augmentation (PVsyst + BESS model)",
            "Design electrical integration (shared POI, MV bus, transformer)",
            "Analyze revenue stacking (energy arbitrage + ancillary + capacity)",
            "Coordinate SLD & protection scheme for hybrid configuration",
            "Simulate annual performance with hourly dispatch model",
        ],
        "outputs": [
            "Hybrid System Sizing Report (.docx)",
            "HPC Functional Specification (.docx)",
            "Curtailment Reduction Analysis (.xlsx)",
            "Annual Energy Yield & Revenue Model (.xlsx)",
            "Hybrid SLD & Protection Scheme Drawing (.dwg/.pdf)",
            "Hybrid Plant Performance Simulation Report (.docx)",
        ],
    },

    "bess-insurance-expert": {
        "inputs": [
            "Project scope, value, & contract terms",
            "Risk register & hazard identification report",
            "Equipment specifications & vendor warranty terms",
            "Site location & natural hazard data (flood, earthquake, cyclone)",
            "Insurance broker proposals & policy terms",
        ],
        "processes": [
            "Identify insurable risks (CAR, EAR, TPL, DSU, cargo)",
            "Specify coverage requirements per contract & lender requirements",
            "Review broker proposals & negotiate policy terms",
            "Coordinate property damage & business interruption valuations",
            "Manage claims process for insured events",
            "Review policy exclusions (thermal runaway, cyber, war)",
            "Ensure compliance with lender's insurance covenants",
        ],
        "outputs": [
            "Insurance Requirement Specification (.docx)",
            "Insurance Coverage Summary Matrix (.xlsx)",
            "Policy Review & Gap Analysis Report (.docx)",
            "Claims Management Report (.docx)",
            "Certificate of Insurance (COI) Register (.xlsx)",
        ],
    },

    "bess-internal-auditor": {
        "inputs": [
            "Company quality management system (ISO 9001) documentation",
            "Project procedures & work instructions",
            "Previous audit findings & corrective action status",
            "Regulatory compliance requirements",
            "Financial controls & procurement procedures",
        ],
        "processes": [
            "Develop annual internal audit plan & schedule",
            "Prepare audit checklists per ISO 19011 methodology",
            "Conduct document review & on-site audit interviews",
            "Identify non-conformances (major, minor, observations)",
            "Issue audit findings & corrective action requests (CARs)",
            "Track CAR closure & verify corrective action effectiveness",
            "Report audit results to management review meeting",
        ],
        "outputs": [
            "Internal Audit Plan (.docx)",
            "Audit Checklist (.xlsx)",
            "Audit Finding Report (.docx)",
            "Corrective Action Request (CAR) Log (.xlsx)",
            "Management Review Presentation (.pptx)",
        ],
    },

    "bess-ip-patent-expert": {
        "inputs": [
            "Company technology portfolio & innovation disclosures",
            "Patent landscape search results for BESS technologies",
            "Competitor patent filings & published applications",
            "Licensing agreements & freedom-to-operate requirements",
            "Trade secret & know-how inventory",
        ],
        "processes": [
            "Conduct patent landscape analysis for target technology area",
            "Perform freedom-to-operate (FTO) analysis before product launch",
            "Draft patent applications for novel BESS innovations",
            "File patent applications in target jurisdictions (US, EU, KR, JP, CN)",
            "Manage patent prosecution & respond to office actions",
            "Negotiate licensing agreements (in-bound & out-bound)",
            "Monitor competitor IP activity & infringement risks",
        ],
        "outputs": [
            "Patent Landscape Report (.docx/.pdf)",
            "Freedom-to-Operate (FTO) Opinion (.docx)",
            "Patent Application Draft (.docx)",
            "IP Portfolio Status Report (.xlsx)",
            "Licensing Agreement Review (.docx)",
        ],
    },

    "bess-it-infra": {
        "inputs": [
            "SCADA/EMS system architecture requirements",
            "Cybersecurity requirements (IEC 62351, NERC CIP)",
            "Network topology & communication protocol list (Modbus, DNP3, IEC 61850)",
            "Server & workstation hardware specifications",
            "Data storage & backup requirements",
            "Remote monitoring & VPN access requirements",
        ],
        "processes": [
            "Design IT network architecture (OT/IT segmentation, DMZ)",
            "Specify server infrastructure (SCADA server, historian, HMI)",
            "Configure firewalls, switches, & network security policies",
            "Implement cybersecurity controls per IEC 62443 / NERC CIP",
            "Set up data historian & time-series database",
            "Configure remote access VPN with multi-factor authentication",
            "Perform penetration testing & vulnerability assessment",
            "Establish backup, disaster recovery, & business continuity plan",
        ],
        "outputs": [
            "IT/OT Network Architecture Diagram (.vsd/.pdf)",
            "Cybersecurity Policy Document (.docx)",
            "Server & Hardware Specification Sheet (.xlsx)",
            "Firewall Rule Configuration Document (.xlsx)",
            "Disaster Recovery Plan (.docx)",
            "Penetration Test Report (.docx/.pdf)",
        ],
    },

    "bess-knowledge-manager": {
        "inputs": [
            "Lessons learned from previous BESS projects",
            "Engineering standards & procedures library",
            "Project documentation repository structure",
            "Staff competency profiles & training records",
            "Industry best practice publications & guidelines",
        ],
        "processes": [
            "Design knowledge management system (KMS) taxonomy & structure",
            "Capture lessons learned at project milestones",
            "Maintain engineering standards & template library",
            "Organize document management system (DMS) with metadata tagging",
            "Facilitate knowledge sharing sessions & communities of practice",
            "Develop onboarding knowledge packs for new team members",
            "Track KMS usage metrics & content freshness",
        ],
        "outputs": [
            "Knowledge Management System (KMS) Framework (.docx)",
            "Lessons Learned Database (.xlsx / web portal)",
            "Engineering Template Library (folder structure)",
            "Onboarding Knowledge Pack (.docx/.pptx)",
            "KMS Usage & Metrics Report (.xlsx)",
        ],
    },

    "bess-legal-expert": {
        "inputs": [
            "EPC contract (FIDIC Silver Book / bespoke)",
            "Equipment supply agreements & vendor contracts",
            "Land lease / purchase agreements",
            "Regulatory framework for target jurisdiction",
            "Corporate governance & compliance policies",
        ],
        "processes": [
            "Review & negotiate EPC contract terms (risk allocation, LD, warranty)",
            "Draft & review equipment supply agreements",
            "Advise on regulatory compliance (energy law, environmental law)",
            "Manage dispute resolution process (negotiation, mediation, arbitration)",
            "Review land rights, easements, & right-of-way agreements",
            "Ensure corporate governance & anti-corruption compliance",
            "Support project finance legal documentation (SPA, SHA, facility agreement)",
        ],
        "outputs": [
            "Contract Review & Risk Commentary (.docx)",
            "Negotiation Position Paper (.docx)",
            "Legal Compliance Checklist (.xlsx)",
            "Dispute Resolution Strategy Document (.docx)",
            "Legal Opinion Letter (.docx/.pdf)",
        ],
    },

    "bess-logistics-expert": {
        "inputs": [
            "Equipment BOM with dimensions, weights, & quantities",
            "Vendor factory locations & manufacturing schedule",
            "Site location & access route survey",
            "Shipping regulations for lithium-ion batteries (IMDG, IATA DGR)",
            "Customs & import duty requirements for target country",
        ],
        "processes": [
            "Plan shipping mode selection (sea, rail, road, multimodal)",
            "Obtain dangerous goods shipping classification & documentation",
            "Coordinate container loading plan & securing method",
            "Manage customs clearance & import permits",
            "Arrange heavy-lift transport for transformers & large equipment",
            "Track shipments from factory to site (GPS / carrier portal)",
            "Coordinate site receiving inspection & laydown area allocation",
            "Process insurance claims for damaged / delayed shipments",
        ],
        "outputs": [
            "Logistics Master Plan (.docx)",
            "Shipping Schedule Tracker (.xlsx)",
            "Dangerous Goods Documentation Package",
            "Customs Clearance Document Set",
            "Container Loading Plan (.pdf)",
            "Site Delivery & Receiving Report (.xlsx)",
        ],
    },

    "bess-network-engineer": {
        "inputs": [
            "BESS SCADA/EMS communication requirements",
            "Site layout & equipment locations",
            "Communication protocol list (Modbus TCP, DNP3, IEC 61850, MQTT)",
            "Grid operator communication interface requirements",
            "Cybersecurity & network segmentation requirements",
        ],
        "processes": [
            "Design communication network architecture (fiber, Ethernet, serial)",
            "Specify managed switches, routers, & media converters",
            "Design fiber optic cable routing & termination plan",
            "Configure VLAN segmentation for OT / IT / DMZ zones",
            "Implement redundancy (ring topology, RSTP/PRP/HSR)",
            "Set up time synchronization (PTP IEEE 1588 / GPS NTP)",
            "Perform network commissioning & communication loop tests",
        ],
        "outputs": [
            "Communication Network Architecture Diagram (.vsd/.pdf)",
            "Network Equipment Specification Sheet (.xlsx)",
            "Fiber Optic Cable Schedule & Routing Drawing (.dwg/.pdf)",
            "VLAN & IP Address Allocation Table (.xlsx)",
            "Network Commissioning Test Report (.docx)",
        ],
    },

    "bess-om-expert": {
        "inputs": [
            "Equipment O&M manuals from vendors (battery, PCS, transformer)",
            "As-built drawings & equipment datasheets",
            "Warranty terms & guaranteed performance parameters",
            "SCADA/EMS monitoring system specifications",
            "Spare parts list & recommended stock levels",
        ],
        "processes": [
            "Develop Operations & Maintenance (O&M) plan & SOPs",
            "Establish preventive maintenance schedule (daily/weekly/monthly/annual)",
            "Implement condition-based monitoring & predictive maintenance",
            "Manage CMMS for work orders, PM tasks, & inventory",
            "Track KPIs: availability, RTE, capacity retention, MTBF",
            "Coordinate battery augmentation & replacement planning",
            "Manage warranty claims & OEM service contracts",
            "Train operations staff on SOPs & emergency procedures",
        ],
        "outputs": [
            "O&M Plan (.docx)",
            "Preventive Maintenance Schedule (.xlsx)",
            "Monthly O&M Performance Report (.xlsx/.pptx)",
            "Spare Parts Inventory & Reorder Report (.xlsx)",
            "Warranty Claim Log (.xlsx)",
            "Annual Performance Summary Report (.docx)",
        ],
    },

    "bess-pcs-expert": {
        "inputs": [
            "BESS system capacity (MW/MWh) & DC voltage range",
            "Grid voltage & frequency requirements",
            "Grid code requirements (FRT, reactive power, ROCOF, FFR)",
            "PCS vendor datasheets & performance curves",
            "Cooling system specifications (air / liquid)",
            "Communication protocol requirements (Modbus, CAN, IEC 61850)",
        ],
        "processes": [
            "Select PCS topology (2-level, 3-level, modular multilevel)",
            "Size PCS power rating with derating for altitude & temperature",
            "Verify DC voltage window compatibility with battery string",
            "Evaluate PCS efficiency curve & weighted efficiency",
            "Review harmonic distortion (THDi, THDv) compliance",
            "Define PCS control modes (grid-following, grid-forming, droop)",
            "Specify PCS protection settings (AC/DC OV, OC, anti-islanding)",
            "Coordinate PCS-BMS communication interface & control signals",
        ],
        "outputs": [
            "PCS Selection & Sizing Report (.docx)",
            "PCS Technical Specification (.docx/.pdf)",
            "PCS Efficiency Analysis (.xlsx)",
            "Harmonic Distortion Compliance Report (.docx)",
            "PCS Control Mode Functional Specification (.docx)",
            "PCS-BMS Interface Specification (.docx)",
        ],
    },

    "bess-permit-asia": {
        "inputs": [
            "Project site location & capacity (MW/MWh)",
            "Target country regulations (Korea, Japan, Taiwan, India, Philippines)",
            "Local government permit application forms",
            "Environmental & fire safety assessment requirements",
            "Grid connection approval requirements (KEPCO, TEPCO, Taipower)",
        ],
        "processes": [
            "Identify all required permits per jurisdiction (construction, electrical, fire, environmental)",
            "Prepare permit application documents in local language",
            "Submit applications to relevant authorities (city/province/national)",
            "Respond to authority review comments & requests for information",
            "Coordinate third-party inspections required for permits",
            "Track permit approval timelines & update project schedule",
            "Obtain final permits & maintain compliance during construction",
        ],
        "outputs": [
            "Permit Requirements Matrix by jurisdiction (.xlsx)",
            "Permit Application Package (per authority)",
            "Permit Tracking Register (.xlsx)",
            "Authority Correspondence Log (.xlsx)",
            "Permit Approval Certificates",
        ],
    },

    "bess-permit-english": {
        "inputs": [
            "Project site location & capacity (MW/MWh)",
            "Target country regulations (USA, UK, Australia, Canada)",
            "Local planning / zoning authority requirements",
            "Environmental assessment requirements (NEPA, CEQA, EPBC Act)",
            "Fire authority (AHJ) requirements (NFPA 855, CFA)",
        ],
        "processes": [
            "Identify federal, state/provincial, & local permit requirements",
            "Prepare Development Application / Conditional Use Permit documents",
            "Submit environmental review documents (NEPA EA/EIS, EPBC referral)",
            "Coordinate fire department review & NFPA 855 compliance submission",
            "Engage with planning authority & community stakeholder consultations",
            "Respond to public comments & authority conditions of approval",
            "Track permit milestones & maintain regulatory compliance",
        ],
        "outputs": [
            "Permit Requirements Checklist (.xlsx)",
            "Development Application Package (.pdf)",
            "Environmental Review Submission (.docx/.pdf)",
            "Fire Authority Submission Package (.pdf)",
            "Permit Tracking Schedule (.xlsx)",
            "Authority Approval Letters & Conditions",
        ],
    },

    "bess-permit-europe": {
        "inputs": [
            "Project site location & capacity (MW/MWh)",
            "Target country regulations (Germany, Spain, Italy, France, Poland, Romania)",
            "EU Directive requirements (EIA Directive, Seveso III, RED II)",
            "National grid operator requirements (TSO/DSO)",
            "Municipal planning & building permit requirements",
        ],
        "processes": [
            "Identify EU & national-level permit requirements",
            "Prepare Environmental Impact Assessment per EU EIA Directive",
            "Submit building permit application to municipal authority",
            "Apply for grid connection permit from TSO/DSO",
            "Coordinate Seveso III assessment (if lithium-ion threshold exceeded)",
            "Respond to authority review comments & public consultations",
            "Obtain all permits & track validity periods",
            "Maintain compliance with REACH & waste battery directive",
        ],
        "outputs": [
            "EU/National Permit Matrix (.xlsx)",
            "EIA Report per EU Directive (.docx/.pdf)",
            "Building Permit Application Package",
            "Grid Connection Permit Application",
            "Seveso III Assessment Report (.docx)",
            "Permit Register with validity dates (.xlsx)",
        ],
    },

    "bess-power-market-expert": {
        "inputs": [
            "Electricity market rules (ERCOT, PJM, AEMO, EPEX, KPX)",
            "Historical market price data (LMP, ancillary services, capacity)",
            "BESS system specifications (MW, MWh, RTE, degradation curve)",
            "Grid service product definitions (FFR, FCAS, regulation, spinning reserve)",
            "Renewable energy certificate (REC) & carbon credit pricing",
        ],
        "processes": [
            "Analyze revenue streams: energy arbitrage, ancillary services, capacity",
            "Model optimal dispatch strategy for revenue maximization",
            "Stack multiple revenue streams & assess cannibalization effects",
            "Forecast market prices using historical data & fundamentals",
            "Evaluate merchant vs contracted revenue risk profile",
            "Assess tolling agreement & PPA structures",
            "Model battery degradation cost per cycle in dispatch optimization",
            "Benchmark revenue projections against industry analyst reports",
        ],
        "outputs": [
            "Revenue Model (.xlsx) with hourly dispatch simulation",
            "Market Analysis Report (.docx/.pdf)",
            "Revenue Stacking Summary (.xlsx)",
            "Dispatch Strategy Recommendation (.docx)",
            "Merchant Risk Assessment (.docx)",
            "PPA / Tolling Agreement Term Sheet Review (.docx)",
        ],
    },

    "bess-power-system-analyst": {
        "inputs": [
            "Grid network model (PSS/E, ETAP, PowerFactory, PSCAD)",
            "BESS system data (MW, MWh, PCS impedance, transformer data)",
            "Utility short-circuit data at POI",
            "Grid code requirements (fault ride-through, voltage regulation)",
            "Existing generation & load data at POI",
        ],
        "processes": [
            "Perform load flow study (steady-state voltage & power flow)",
            "Conduct short-circuit analysis (3-phase, SLG, DLG fault levels)",
            "Run protection coordination study & relay settings verification",
            "Perform voltage stability & reactive power capability analysis",
            "Conduct harmonic analysis (THD at POI vs IEEE 519 / IEC 61000-3)",
            "Run transient stability simulation (fault ride-through, frequency response)",
            "Perform electromagnetic transient (EMT) study if required by utility",
        ],
        "outputs": [
            "Load Flow Study Report (.docx/.pdf)",
            "Short-Circuit Study Report (.docx/.pdf)",
            "Protection Coordination Study (.docx/.pdf)",
            "Harmonic Analysis Report (.docx/.pdf)",
            "Transient Stability Study Report (.docx/.pdf)",
            "Power System Study Summary for utility submission (.pdf)",
        ],
    },

    "bess-precom-report": {
        "inputs": [
            "Equipment installation records & as-built drawings",
            "Vendor pre-commissioning procedures & checklists",
            "Inspection & Test Plan (ITP) completion records",
            "Cable insulation test (Megger) results",
            "Protection relay injection test results",
        ],
        "processes": [
            "Compile pre-commissioning checksheet completion status",
            "Verify all ITP hold & witness points are signed off",
            "Review cable insulation resistance test results vs acceptance criteria",
            "Confirm protection relay injection test results pass",
            "Verify grounding continuity test results",
            "Check SCADA/BMS point-to-point verification status",
            "Consolidate punch-list items & categorize (A/B/C priority)",
            "Prepare pre-commissioning completion certificate",
        ],
        "outputs": [
            "Pre-Commissioning Completion Report (.docx/.pdf)",
            "Pre-Commissioning Checksheet Package (.xlsx/.pdf)",
            "Insulation Resistance Test Report (.xlsx)",
            "Relay Injection Test Report (.xlsx)",
            "Punch-list Register (.xlsx)",
            "Pre-Commissioning Completion Certificate (.docx)",
        ],
    },

    "bess-presentation-designer": {
        "inputs": [
            "Technical content & data from engineering teams",
            "Project photos & 3D renderings",
            "Company branding guidelines & templates",
            "Target audience profile (investor, client, regulator, internal)",
            "Presentation purpose & key messages",
        ],
        "processes": [
            "Define presentation structure & storyline flow",
            "Design slide layouts per corporate branding guidelines",
            "Create data visualization charts (S-curves, Gantt, dashboards)",
            "Develop technical diagrams (SLD, system architecture, process flow)",
            "Incorporate project photos & 3D renderings",
            "Review content accuracy with engineering subject matter experts",
            "Finalize presentation with animation & transition effects",
        ],
        "outputs": [
            "Technical Presentation (.pptx)",
            "Executive Summary Slide Deck (.pptx)",
            "Project Fact Sheet / One-Pager (.pdf)",
            "Data Visualization Charts (.png/.svg)",
            "Infographic Poster (.pdf/.ai)",
        ],
    },

    "bess-procurement-data": {
        "inputs": [
            "Purchase Orders (PO) & vendor contracts",
            "Vendor quotation comparison data",
            "Equipment delivery & logistics tracking data",
            "Invoice & payment milestone records",
            "Approved Vendor List (AVL) & performance history",
        ],
        "processes": [
            "Maintain procurement database (PO, vendor, delivery, cost)",
            "Track PO status lifecycle (issued → acknowledged → shipped → received)",
            "Generate vendor performance scorecards (quality, delivery, cost)",
            "Analyze procurement spend by category & vendor",
            "Monitor lead time trends & flag schedule risks",
            "Reconcile invoices against PO milestones & receipts",
            "Produce procurement status dashboards for management",
        ],
        "outputs": [
            "Procurement Status Report (.xlsx/.pptx)",
            "Vendor Performance Scorecard (.xlsx)",
            "Spend Analysis Report (.xlsx)",
            "PO Tracking Register (.xlsx)",
            "Invoice Reconciliation Report (.xlsx)",
        ],
    },

    "bess-sales-manager": {
        "inputs": [
            "Market intelligence & project pipeline data",
            "Client RFP / RFI / EOI documents",
            "Company capability statement & reference project list",
            "Competitor analysis & market share data",
            "Pricing model & margin targets",
        ],
        "processes": [
            "Identify & qualify BESS project opportunities (lead scoring)",
            "Develop client relationship management (CRM) strategy",
            "Prepare technical & commercial proposals for RFPs",
            "Coordinate bid/no-bid decision with management",
            "Present company capabilities & technical solution to clients",
            "Negotiate contract terms & pricing with clients",
            "Track sales pipeline & conversion metrics",
            "Coordinate handover from sales to project execution team",
        ],
        "outputs": [
            "Sales Pipeline Report (.xlsx/.pptx)",
            "Technical & Commercial Proposal (.docx/.pdf)",
            "Client Presentation (.pptx)",
            "Bid Decision Matrix (.xlsx)",
            "Contract Negotiation Summary (.docx)",
            "Win/Loss Analysis Report (.docx)",
        ],
    },

    "bess-standards-analyst": {
        "inputs": [
            "Project scope & target market(s)",
            "Applicable standards list (IEEE, IEC, NFPA, UL, EN, KS, AS/NZS)",
            "Equipment vendor compliance certificates",
            "Regulatory requirements per jurisdiction",
            "Client specification & standards callouts",
        ],
        "processes": [
            "Compile master standards applicability matrix for project",
            "Map project deliverables to applicable standard clauses",
            "Review equipment vendor compliance certificates vs requirements",
            "Identify gaps between client specification & applicable standards",
            "Track standards revision updates & impact on project",
            "Coordinate standards compliance review with engineering disciplines",
            "Prepare standards compliance declaration for client/authority",
        ],
        "outputs": [
            "Standards Applicability Matrix (.xlsx)",
            "Standards Compliance Checklist (.xlsx)",
            "Gap Analysis Report (.docx)",
            "Standards Compliance Declaration (.docx)",
            "Regulatory Compliance Register (.xlsx)",
        ],
    },

    "bess-standards-australia": {
        "inputs": [
            "AS/NZS 3000 (Wiring Rules) & AS/NZS 3008 (Cable Selection)",
            "AS 5139 (Electrical installations — Safety of BESS)",
            "AS/NZS 4777.2 (Grid connection of inverter systems)",
            "CFA/RFS fire authority guidelines for BESS",
            "AEMO grid connection requirements & NER rules",
        ],
        "processes": [
            "Map project design to AS 5139 safety requirements",
            "Verify cable sizing per AS/NZS 3008 with Australian derating factors",
            "Ensure PCS compliance with AS/NZS 4777.2 grid connection standard",
            "Coordinate CFA/RFS fire authority review & separation distances",
            "Review AEMO Generator Performance Standards (GPS) compliance",
            "Prepare compliance documentation for AER / state regulator",
            "Track Australian standards updates & amendments",
        ],
        "outputs": [
            "AS 5139 Compliance Checklist (.xlsx)",
            "AS/NZS 4777.2 Grid Compliance Report (.docx)",
            "CFA/RFS Fire Authority Submission Package (.pdf)",
            "AEMO GPS Compliance Register (.xlsx)",
            "Australian Standards Compliance Matrix (.xlsx)",
        ],
    },

    "bess-standards-eu": {
        "inputs": [
            "IEC 62619 (Safety requirements for Li-ion batteries)",
            "IEC 62933 series (Electrical energy storage systems)",
            "EN 50549 (Requirements for generating plants — grid connection)",
            "EU Low Voltage Directive (LVD) & EMC Directive",
            "EU Battery Regulation (2023/1542) requirements",
        ],
        "processes": [
            "Map project design to IEC 62619 & IEC 62933 requirements",
            "Verify CE marking requirements (LVD, EMC, Machinery Directive)",
            "Ensure grid connection compliance with EN 50549 / country-specific code",
            "Assess EU Battery Regulation compliance (carbon footprint, recycled content, due diligence)",
            "Coordinate with Notified Body for CE certification if required",
            "Prepare EU Declaration of Conformity documentation",
            "Track EU regulatory updates (taxonomy, battery passport, CBAM)",
        ],
        "outputs": [
            "IEC 62619 / 62933 Compliance Matrix (.xlsx)",
            "CE Marking Assessment Report (.docx)",
            "EN 50549 Grid Compliance Checklist (.xlsx)",
            "EU Battery Regulation Compliance Plan (.docx)",
            "EU Declaration of Conformity (.docx/.pdf)",
        ],
    },

    "bess-standards-japan": {
        "inputs": [
            "JIS C 8715 series (Safety of Li-ion batteries for industrial use)",
            "JEC 2470 (Storage battery systems)",
            "METI ordinances for electricity business",
            "TEPCO/Kansai EPCO grid connection technical requirements",
            "Fire Service Act requirements for battery installations",
        ],
        "processes": [
            "Map project design to JIS C 8715 safety requirements",
            "Verify compliance with METI electrical safety regulations",
            "Ensure grid connection compliance with utility technical requirements",
            "Coordinate Fire Service Act notification & fire prevention plan",
            "Review Building Standards Act requirements for BESS structures",
            "Prepare documentation for METI pre-use inspection",
            "Track JIS/JEC standards updates & regulatory changes",
        ],
        "outputs": [
            "JIS/JEC Compliance Matrix (.xlsx)",
            "METI Regulatory Compliance Checklist (.xlsx)",
            "Grid Connection Compliance Report (.docx)",
            "Fire Service Act Notification Package",
            "METI Pre-use Inspection Submission (.pdf)",
        ],
    },

    "bess-standards-korea": {
        "inputs": [
            "KS C IEC 62619 (Korean adoption of IEC 62619)",
            "KEC (Korean Electrical Code) requirements",
            "KEPCO grid connection technical standards",
            "MOTIE (Ministry of Trade, Industry & Energy) ESS safety standards",
            "KFS (Korea Fire Service) fire safety requirements for ESS",
        ],
        "processes": [
            "Map project design to MOTIE ESS safety reinforcement measures",
            "Verify compliance with KEC for electrical installations",
            "Ensure KEPCO grid connection technical requirements compliance",
            "Coordinate KFS fire safety review (separation, suppression, detection)",
            "Review KS certification requirements for battery & PCS",
            "Prepare documentation for electrical safety inspection (KESCO)",
            "Track Korean ESS safety policy updates & regulatory changes",
        ],
        "outputs": [
            "KS/KEC Compliance Matrix (.xlsx)",
            "MOTIE ESS Safety Compliance Checklist (.xlsx)",
            "KEPCO Grid Connection Compliance Report (.docx)",
            "KFS Fire Safety Submission Package (.pdf)",
            "KESCO Inspection Preparation Package (.xlsx)",
        ],
    },

    "bess-standards-poland": {
        "inputs": [
            "Polish Energy Law (Prawo energetyczne) requirements",
            "PN-EN standards (Polish adoption of EN/IEC)",
            "PSE (Polish TSO) grid connection requirements",
            "URE (Energy Regulatory Office) licensing requirements",
            "Polish building code & fire safety regulations",
        ],
        "processes": [
            "Map project design to Polish Energy Law requirements",
            "Verify compliance with PN-EN standards for electrical equipment",
            "Ensure PSE grid connection technical requirements compliance",
            "Coordinate URE licensing & concession requirements",
            "Review Polish building permit & fire safety requirements",
            "Prepare documentation for UDT (Office of Technical Inspection)",
            "Track Polish energy market regulatory changes",
        ],
        "outputs": [
            "PN-EN Standards Compliance Matrix (.xlsx)",
            "PSE Grid Connection Compliance Report (.docx)",
            "URE Licensing Application Package",
            "Polish Building & Fire Safety Compliance Checklist (.xlsx)",
            "UDT Inspection Preparation Package (.xlsx)",
        ],
    },

    "bess-standards-romania": {
        "inputs": [
            "ANRE (Romanian Energy Regulatory Authority) regulations",
            "Transelectrica (Romanian TSO) grid connection requirements",
            "Romanian adoption of EN/IEC standards",
            "Romanian building & environmental permit requirements",
            "ISU (fire authority) fire safety requirements",
        ],
        "processes": [
            "Map project design to ANRE technical regulations",
            "Verify compliance with Romanian-adopted EN/IEC standards",
            "Ensure Transelectrica grid connection ATR requirements compliance",
            "Coordinate ISU fire safety review & obtain fire safety permit",
            "Review Romanian building permit & urbanism certificate requirements",
            "Prepare documentation for ISCIR (pressure/equipment inspection)",
            "Track ANRE regulatory updates & support scheme changes",
        ],
        "outputs": [
            "ANRE Regulatory Compliance Matrix (.xlsx)",
            "Transelectrica ATR Compliance Report (.docx)",
            "Romanian EN/IEC Standards Checklist (.xlsx)",
            "ISU Fire Safety Permit Submission (.pdf)",
            "ISCIR Inspection Preparation Package (.xlsx)",
        ],
    },

    "bess-standards-uk": {
        "inputs": [
            "BS EN 62619 (UK adoption of IEC 62619)",
            "G99 / G100 (Grid connection requirements for generators)",
            "BS 7671 (IET Wiring Regulations)",
            "NFCC guidance for BESS fire safety",
            "National Grid ESO Grid Code requirements",
        ],
        "processes": [
            "Map project design to BS EN 62619 safety requirements",
            "Verify G99 compliance for grid connection (Type A/B/C/D categories)",
            "Ensure BS 7671 compliance for electrical installation design",
            "Coordinate NFCC fire safety review & fire strategy submission",
            "Review National Grid ESO Grid Code compliance (frequency response, FRT)",
            "Prepare DNO/IDNO application & G99 compliance documentation",
            "Track UK regulatory updates (BEIS, Ofgem, Grid Code modifications)",
        ],
        "outputs": [
            "BS EN 62619 Compliance Checklist (.xlsx)",
            "G99 Grid Connection Compliance Report (.docx)",
            "BS 7671 Electrical Installation Compliance Matrix (.xlsx)",
            "NFCC Fire Safety Strategy Document (.docx)",
            "DNO Application & G99 Submission Package (.pdf)",
        ],
    },

    "bess-standards-usa": {
        "inputs": [
            "IEEE 1547 (Interconnection of DER with EPS)",
            "NEC Article 706 (Energy Storage Systems)",
            "NFPA 855 (Standard for Installation of ESS)",
            "UL 9540 / UL 9540A (ESS safety & thermal runaway testing)",
            "NERC reliability standards (if applicable)",
            "State-specific interconnection requirements (CAISO, NYISO, ERCOT)",
        ],
        "processes": [
            "Map project design to NEC Article 706 requirements",
            "Verify NFPA 855 compliance (separation, ventilation, signage)",
            "Ensure UL 9540 listing & UL 9540A test report availability",
            "Verify IEEE 1547 interconnection compliance (Category I/II/III)",
            "Coordinate AHJ (Authority Having Jurisdiction) plan review",
            "Prepare NEC & NFPA compliance documentation for permit submittal",
            "Review state-specific incentive program technical requirements (IRA, ITC)",
            "Track US code cycle updates (NEC 2026, NFPA 855 revisions)",
        ],
        "outputs": [
            "NEC Article 706 Compliance Checklist (.xlsx)",
            "NFPA 855 Compliance Report (.docx)",
            "UL 9540 / 9540A Compliance Matrix (.xlsx)",
            "IEEE 1547 Interconnection Compliance Report (.docx)",
            "AHJ Submission Package (.pdf)",
            "US Standards Compliance Summary (.xlsx)",
        ],
    },

    "bess-substation-engineer": {
        "inputs": [
            "Grid voltage level & interconnection requirements",
            "BESS capacity (MW) & number of PCS/transformer units",
            "Utility protection & metering requirements",
            "Site layout constraints & available footprint",
            "Applicable substation standards (IEEE C57, IEC 62271, AS 2067)",
        ],
        "processes": [
            "Design substation layout (outdoor AIS or indoor GIS configuration)",
            "Size main power transformer (MVA, impedance, cooling, vector group)",
            "Select HV/MV switchgear (circuit breaker, disconnect, earthing switch)",
            "Design bus configuration (single bus, double bus, ring bus)",
            "Specify protection relay scheme (differential, distance, overcurrent)",
            "Design metering & revenue metering system",
            "Coordinate civil & structural design for substation foundations",
            "Prepare substation SLD & general arrangement drawing",
        ],
        "outputs": [
            "Substation Design Report (.docx)",
            "Substation SLD (.dwg/.pdf)",
            "Substation General Arrangement Drawing (.dwg/.pdf)",
            "Transformer Specification Sheet (.docx)",
            "Switchgear Selection Schedule (.xlsx)",
            "Protection Relay Scheme Drawing (.dwg/.pdf)",
            "Substation Equipment BOM (.xlsx)",
        ],
    },

    "bess-tax-accountant": {
        "inputs": [
            "Project financial model & CAPEX breakdown",
            "Tax regulations for target jurisdiction",
            "Investment Tax Credit (ITC) / Production Tax Credit (PTC) eligibility data",
            "Depreciation schedule options (MACRS, straight-line)",
            "Transfer pricing & intercompany transaction data",
            "Government incentive program guidelines",
        ],
        "processes": [
            "Assess tax incentive eligibility (IRA ITC/PTC, state incentives)",
            "Calculate optimal depreciation schedule (5-yr MACRS for US BESS)",
            "Structure project entity for tax efficiency (partnership flip, sale-leaseback)",
            "Prepare tax equity investor financial projections",
            "Review transfer pricing compliance for cross-border transactions",
            "File tax returns & manage tax compliance calendar",
            "Monitor legislative changes impacting energy storage tax treatment",
        ],
        "outputs": [
            "Tax Incentive Eligibility Assessment (.docx)",
            "Depreciation Schedule (.xlsx)",
            "Tax Structure Recommendation Memo (.docx)",
            "Tax Equity Model (.xlsx)",
            "Tax Compliance Calendar (.xlsx)",
            "Tax Return Filing Package",
        ],
    },

    "bess-tool-developer": {
        "inputs": [
            "Internal tool requirements from engineering teams",
            "Existing calculation spreadsheets & manual workflows",
            "Data sources (SCADA, ERP, project databases)",
            "User interface & user experience requirements",
            "Technology stack preferences (Python, JavaScript, cloud platform)",
        ],
        "processes": [
            "Gather requirements & define tool scope with stakeholders",
            "Design software architecture & data model",
            "Develop backend logic (calculation engines, API integrations)",
            "Build frontend interface (web dashboard, CLI tool, Excel add-in)",
            "Implement automated testing (unit tests, integration tests)",
            "Deploy tool to production environment (cloud / on-premise)",
            "Create user documentation & conduct training sessions",
            "Maintain tool & implement feature enhancements based on feedback",
        ],
        "outputs": [
            "Software Requirements Specification (.docx)",
            "Tool Source Code Repository (Git)",
            "User Manual & Quick Start Guide (.docx/.pdf)",
            "Automated Test Suite & CI/CD Pipeline",
            "Deployed Application (web URL / executable)",
            "Release Notes & Change Log (.md)",
        ],
    },

    "bess-training-expert": {
        "inputs": [
            "Project scope & technology overview",
            "Target audience competency assessment results",
            "Equipment O&M manuals & vendor training materials",
            "Safety procedures & regulatory training requirements",
            "Company training policy & LMS platform specifications",
        ],
        "processes": [
            "Conduct training needs analysis (TNA) per role & competency gap",
            "Develop training curriculum & learning objectives",
            "Create training materials (presentations, manuals, e-learning modules)",
            "Deliver classroom & hands-on training sessions",
            "Conduct practical assessments & competency evaluations",
            "Manage training records in Learning Management System (LMS)",
            "Evaluate training effectiveness (Kirkpatrick Level 1-3)",
            "Update training materials based on lessons learned & feedback",
        ],
        "outputs": [
            "Training Needs Analysis Report (.docx)",
            "Training Curriculum & Schedule (.xlsx)",
            "Training Materials Package (.pptx/.pdf/.mp4)",
            "Competency Assessment Records (.xlsx)",
            "Training Completion Certificates (.pdf)",
            "Training Effectiveness Report (.docx)",
        ],
    },

    "bess-transformer-expert": {
        "inputs": [
            "BESS system capacity (MW) & voltage levels (LV/MV/HV)",
            "PCS output voltage & current specifications",
            "Grid connection voltage & short-circuit level at POI",
            "Cooling method constraints (ONAN, ONAF, dry-type AN/AF)",
            "Applicable transformer standards (IEEE C57, IEC 60076, AS 60076)",
            "Site environmental conditions (altitude, ambient temperature)",
        ],
        "processes": [
            "Size transformer MVA rating with overload & derating considerations",
            "Select impedance value (typically 5.75-8%) for fault current limitation",
            "Specify vector group (Dyn11 typical for BESS step-up)",
            "Define cooling class & temperature rise limits",
            "Specify tap changer requirements (OLTC vs DETC, range, steps)",
            "Calculate transformer losses (no-load, load losses) & efficiency",
            "Review factory acceptance test (FAT) protocol (routine, type, special tests)",
            "Coordinate transformer foundation & oil containment design",
        ],
        "outputs": [
            "Transformer Specification Sheet (.docx/.pdf)",
            "Transformer Sizing Calculation (.xlsx)",
            "Transformer Loss Evaluation (.xlsx)",
            "FAT Witness Test Protocol (.docx)",
            "Transformer Foundation & Bund Design Input (.docx)",
            "Transformer Datasheet for vendor bidding (.xlsx)",
        ],
    },

    "bess-translator": {
        "inputs": [
            "Source documents in original language (KO, EN, JP, DE, RO, PL)",
            "Technical glossary & terminology database (BESS/EPC domain)",
            "Client-specified language & formatting requirements",
            "Company style guide & translation memory (TM)",
            "Reference documents & drawings requiring localization",
        ],
        "processes": [
            "Review source document scope & identify technical terminology",
            "Translate technical documents using CAT tools (SDL Trados, memoQ)",
            "Maintain & update BESS/EPC terminology database (bilingual glossary)",
            "Perform self-review & quality assurance (QA) check",
            "Coordinate peer review by domain expert (engineer review)",
            "Localize drawings, diagrams, & UI text as required",
            "Deliver final translation with formatting matching source layout",
        ],
        "outputs": [
            "Translated Technical Document (.docx/.pdf)",
            "BESS/EPC Terminology Glossary (bilingual) (.xlsx)",
            "Translation Memory (TM) File (.tmx)",
            "Localized Drawings & Diagrams (.dwg/.pdf)",
            "Translation Quality Report (.docx)",
        ],
    },
}
