"""
lang_helper.py
Shared translation utility for the BESS EPC Dashboard.
Usage in any page:
    from utils.lang_helper import t
    st.title(t("page_title"))
"""
import streamlit as st

# All translatable strings, keyed by string ID
_TRANSLATIONS = {
    # ─── Common / Sidebar ────────────────────────────────────────────
    "lang_label":    {"KO": "🌐 언어",                          "EN": "🌐 Language"},
    "sidebar_hint":  {"KO": "위 메뉴에서 담당 모듈을 선택하세요.",  "EN": "Select a module from the menu above."},
    "regional_std":  {"KO": "🌐 지역별 엔지니어링 표준 & 컴플라이언스", "EN": "🌐 Regional Engineering Standards & Compliance"},
    "phase_tab_i":   {"KO": "[I] 입력 항목",   "EN": "[I] Inputs"},
    "phase_tab_p":   {"KO": "[P] 프로세스",    "EN": "[P] Process"},
    "phase_tab_o":   {"KO": "[O] 출력물",      "EN": "[O] Outputs"},
    "gen_report":    {"KO": "📄 보고서 생성",   "EN": "📄 Generate Report"},
    "dl_report":     {"KO": "⬇️ 보고서 다운로드 (.txt)", "EN": "⬇️ Download Report (.txt)"},
    "req_inputs":    {"KO": "### 필요 입력 항목",  "EN": "### Required Inputs"},
    "active_procs":  {"KO": "### 수행 프로세스",   "EN": "### Active Processes"},
    "deliverables":  {"KO": "### 납품 출력물",     "EN": "### Deliverable Outputs"},
    "doc_gateway":   {"KO": "#### 문서 생성 게이트웨이", "EN": "#### Document Generation Gateway"},

    # ─── Project Setup (01) ──────────────────────────────────────────
    "p1_caption":    {"KO": "🛤️ **BESS EPC 워크플로우:** [Step 1 (개념)] ➜ Step 2 (시스템 엔지니어링) ➜ ...",
                      "EN": "🛤️ **BESS EPC Workflow:** [Step 1 (Concept)] ➜ Step 2 (System Eng) ➜ ..."},
    "p1_title":      {"KO": "🎯 Step 1: BESS 프로젝트 사양 & 설정",
                      "EN": "🎯 Step 1: BESS Project Specification & Setup"},
    "p1_guide":      {"KO": "💡 **가이드:** BESS 설계의 첫 단계입니다. 발주처 요구사항 또는 초기 사업 기획 데이터를 입력하세요. 값이 입력되면 즉시 저장됩니다.",
                      "EN": "💡 **Guidance:** First step of BESS design. Enter client requirements or initial project planning data. Values are saved immediately and persist across page navigation."},
    "p1_autofill":   {"KO": "🧠 전문가 그룹 샘플 데이터 자동 입력",
                      "EN": "🧠 Auto-fill Expert Defaults"},
    "p1_reset":      {"KO": "🔄 전체 초기화 (Reset All Inputs)",
                      "EN": "🔄 Reset All Inputs"},
    "p1_s1":         {"KO": "1. 일반 프로젝트 정보",  "EN": "1. General Project Info"},
    "p1_s2":         {"KO": "2. 핵심 BESS 용량 산정", "EN": "2. Core BESS Sizing"},
    "p1_s3":         {"KO": "3. 환경 조건",           "EN": "3. Environmental Conditions"},
    "p1_s4":         {"KO": "4. 시스템 효율 & 손실 (전문가 파라미터)", "EN": "4. System Efficiency & Losses (Expert Parameters)"},
    "p1_proj_name":  {"KO": "프로젝트명",              "EN": "Project Name"},
    "p1_market":     {"KO": "설치 국가/지역 (Target Market)", "EN": "Target Market (Country/Region)"},
    "p1_app":        {"KO": "주요 용도 (Grid Application)", "EN": "Grid Application (Primary Use)"},
    "p1_power":      {"KO": "목표 출력 (MW)",          "EN": "Target Power (MW)"},
    "p1_duration":   {"KO": "목표 시간 (Hours)",        "EN": "Target Duration (Hours)"},
    "p1_chem":       {"KO": "배터리 화학 (Chemistry)",  "EN": "Battery Chemistry"},
    "p1_grid_v":     {"KO": "계통 연계 전압 (kV)",      "EN": "Grid Interconnection Voltage (kV)"},
    "p1_max_temp":   {"KO": "최고 주변 온도 (°C)",      "EN": "Max Ambient Temp (°C)"},
    "p1_min_temp":   {"KO": "최저 주변 온도 (°C)",      "EN": "Min Ambient Temp (°C)"},
    "p1_rte":        {"KO": "목표 RTE (왕복 효율) %",   "EN": "Target RTE (Round-Trip Efficiency) %"},
    "p1_rte_help":   {"KO": "배터리 및 PCS 손실을 포함한 AC-to-AC 효율", "EN": "AC-to-AC efficiency including battery and PCS losses."},
    "p1_aux_loss":   {"KO": "보조 전력 손실 (%)",        "EN": "Auxiliary Power Loss (%)"},
    "p1_aux_help":   {"KO": "HVAC, 제어장치, 대기 손실",  "EN": "HVAC, Controls, and Standby losses."},
    "p1_epc_margin": {"KO": "EPC 설계 여유율 (%)",       "EN": "EPC Design Margin (%)"},
    "p1_epc_help":   {"KO": "열화 대비 용량 버퍼",        "EN": "Capacity buffer for degradation."},
    "p1_save_ok":    {"KO": "✅ 모든 설정이 자동 저장되었습니다!",
                      "EN": "✅ All settings auto-saved!"},

    # ─── System Engineering (02) ─────────────────────────────────────
    "p2_caption":    {"KO": "🛤️ **BESS EPC 워크플로우:** Step 1 (개념) ➔ **[Step 2: 시스템 설계]** ➔ Step 3 (3D 해석) ...",
                      "EN": "🛤️ **BESS EPC Workflow:** Step 1 (Concept) ➔ **[Step 2: System Engineering]** ➔ Step 3 (3D/Analysis) ..."},
    "p2_title":      {"KO": "⚙️ 시스템 엔지니어링 모듈",         "EN": "⚙️ System Engineering Module"},
    "p2_arch":       {"KO": "프로젝트 아키텍처 개요",             "EN": "Project Architecture Overview"},
    "p2_agent":      {"KO": "에이전트: **시스템 엔지니어 / 아키텍트 (BESS 전체 용량 산정)**",
                      "EN": "Agent: **System Engineer / Architect (BESS Overall Dimensioning)**"},
    "p2_key_in":     {"KO": "핵심 파라미터 (입력)",              "EN": "Key Parameters (Input)"},
    "p2_pow":        {"KO": "목표 출력 (MW)",                   "EN": "Target Power (MW)"},
    "p2_ene":        {"KO": "목표 에너지 (MWh)",                 "EN": "Target Energy (MWh)"},
    "p2_crate":      {"KO": "C-Rate 요건",                      "EN": "C-Rate Requirement"},
    "p2_sizing":     {"KO": "시스템 규모 산정 결과",              "EN": "System Sizing Output"},
    "p2_duration":   {"KO": "공칭 운전 시간",                   "EN": "Nominal Duration"},
    "p2_nameplate":  {"KO": "필요 배터리 Nameplate (DC MWh)",    "EN": "Required Battery Nameplate (DC MWh)"},
    "p2_enclosure":  {"KO": "필요 배터리 인클로저 (수량)",         "EN": "Required Battery Enclosures"},
    "p2_pcs":        {"KO": "필요 PCS 스키드 (수량)",             "EN": "Required PCS Skids"},
    "p2_inp_cb1":    {"KO": "RFP / 규격서 (계통 요건)",           "EN": "Request for Proposal (RFP) - Grid Req"},
    "p2_inp_cb2":    {"KO": "현장 배치도 (지형 & 경계)",           "EN": "Site Layout (Topography & Boundaries)"},
    "p2_inp_cb3":    {"KO": "발주처 선호 벤더 목록 (BMS, EMS)",   "EN": "Client Preferred Vendor List (BMS, EMS)"},
    "p2_proc_cb1":   {"KO": "총 에너지·출력 스케일링 계산",        "EN": "Calculate total energy and power scaling"},
    "p2_proc_cb2":   {"KO": "기본 SLD 개념도 초안 작성",           "EN": "Draft Single Line Diagram (SLD) Base Concept"},
    "p2_proc_cb3":   {"KO": "E-BOP & C-BOP와 면적 협의",          "EN": "Coordinate with E-BOP & C-BOP for footprint"},
    "p2_out_cb1":    {"KO": "BESS 개념 아키텍처 다이어그램",        "EN": "BESS Conceptual Architecture Diagram"},
    "p2_out_cb2":    {"KO": "고수준 기자재 일람표",               "EN": "High-level Equipment Schedule List"},
    "p2_gen_rep":    {"KO": "📄 시스템 아키텍처 보고서 생성",       "EN": "📄 Generate System Architecture Report"},
    "p2_dl_rep":     {"KO": "⬇️ 시스템 아키텍처 보고서 다운로드 (.txt)", "EN": "⬇️ Download System Architecture Report (.txt)"},

    # ─── E-BOP (04) ──────────────────────────────────────────────────
    "p4_caption":    {"KO": "🛤️ Step 3 (3D 해석) ➔ **[Step 4: E-BOP 설계]** ➔ Step 5 (토목)",
                      "EN": "🛤️ Step 3 (3D/Analysis) ➔ **[Step 4: E-BOP Design]** ➔ Step 5 (Civil)"},
    "p4_title":      {"KO": "⚡ E-BOP 엔지니어 툴킷",            "EN": "⚡ E-BOP Engineer Toolkit"},
    "p4_info":       {"KO": "변압기·케이블·계통보호·접지 설계 도구 모음.",
                      "EN": "Electrical Balance of Plant design tools for Transformer sizing, Cable, Protection, and Grounding."},
    "p4_tab1":       {"KO": "변압기 용량 산정",                   "EN": "Transformer Sizing"},
    "p4_tab2":       {"KO": "케이블 단면적 계산기",                "EN": "Cable Sizing Calculator"},
    "p4_tab3":       {"KO": "접지 저항 계산기",                   "EN": "Grounding Grid Calculator"},
    "p4_tr_title":   {"KO": "PCS 변압기 용량 산정",               "EN": "PCS Transformer Sizing"},
    "p4_tr_pow":     {"KO": "PCS 출력 (MW)",                    "EN": "PCS Output Power (MW)"},
    "p4_tr_pf":      {"KO": "역률",                              "EN": "Power Factor"},
    "p4_tr_eff":     {"KO": "변압기 효율 (%)",                   "EN": "Transformer Efficiency (%)"},
    "p4_tr_volt":    {"KO": "1차 전압 (kV)",                    "EN": "Primary Voltage (kV)"},
    "p4_tr_kva":     {"KO": "필요 변압기 용량 (kVA)",             "EN": "Required Transformer Rating (kVA)"},
    "p4_tr_rec":     {"KO": "권장 표준 규격 (kVA)",              "EN": "Recommended Standard (kVA)"},
    "p4_cable_title":{"KO": "MV/LV 케이블 단면적 산정",           "EN": "MV/LV Cable Cross-Section Sizing"},
    "p4_cable_i":    {"KO": "부하 전류 (A)",                    "EN": "Load Current (A)"},
    "p4_cable_l":    {"KO": "케이블 길이 (m)",                   "EN": "Cable Length (m)"},
    "p4_cable_drop": {"KO": "허용 전압 강하 (%)",                "EN": "Allowable Voltage Drop (%)"},
    "p4_cable_mat":  {"KO": "도체 재질",                         "EN": "Conductor Material"},
    "p4_cable_cu":   {"KO": "동 (Copper)",                      "EN": "Copper"},
    "p4_cable_al":   {"KO": "알루미늄 (Aluminum)",               "EN": "Aluminum"},
    "p4_cable_area": {"KO": "계산 케이블 단면적 (mm²)",           "EN": "Calculated Min Area (mm²)"},
    "p4_cable_std":  {"KO": "권장 표준 단면적 (mm²)",             "EN": "Recommended Standard (mm²)"},
    "p4_gnd_title":  {"KO": "접지 저항 계산기 (Mock)",            "EN": "Grounding Grid Calculator (Mock)"},
    "p4_gnd_desc":   {"KO": "간략 IEEE 80 수식으로 접지 저항 추정.",
                      "EN": "Estimate Grounding Resistance using simplified IEEE 80 equation."},
    "p4_gnd_rho":    {"KO": "토양 비저항 (Ω·m)",                "EN": "Soil Resistivity (Ω·m)"},
    "p4_gnd_area":   {"KO": "접지 격자 면적 (m²)",               "EN": "Grid Area (m²)"},
    "p4_gnd_len":    {"KO": "총 도체 길이 (m)",                  "EN": "Total Conductor Length (m)"},
    "p4_gnd_rg":     {"KO": "예상 접지 저항 (Rg)",               "EN": "Estimated Grid Resistance (Rg)"},
    "p4_gnd_ok":     {"KO": "변전소 접지 목표값 충족 (≤ 1.0 Ω)", "EN": "Target met for Substation Grounding (≤ 1.0 Ω)"},
    "p4_gnd_warn":   {"KO": "일반 장비에는 허용, 변전소 기준 미달. 심타 접지봉 추가 검토.",
                      "EN": "Acceptable for general equipment, but may fail strict substation requirements. Consider deep driven rods."},
    "p4_gnd_err":    {"KO": "저항 과대. 접지 격자 면적 또는 도체 길이 증가 필요.",
                      "EN": "Resistance too high. Increase grid area or conductor length."},

    # ─── C-BOP (05) ──────────────────────────────────────────────────
    "p5_caption":    {"KO": "🛤️ Step 4 (E-BOP) ➔ **[Step 5: 토목 & C-BOP 설계]** ➔ Step 6 (분석)",
                      "EN": "🛤️ Step 4 (E-BOP) ➔ **[Step 5: Civil & C-BOP Design]** ➔ Step 6 (Analytics)"},
    "p5_title":      {"KO": "🏗️ C-BOP 엔지니어 툴킷",            "EN": "🏗️ C-BOP Engineer Toolkit"},
    "p5_info":       {"KO": "기기 패드 규격, 트렌치 경로, HVAC/소방 배치를 위한 Civil BOP 설계 도구.",
                      "EN": "Civil Balance of Plant design tools for Equipment Pad Sizing, Trench Routing, and HVAC/Fire Protection layout."},
    "p5_tab1":       {"KO": "기기 패드 규격 산정",               "EN": "Equipment Pad Sizing"},
    "p5_tab2":       {"KO": "트렌치 & 덕트뱅크 설계",             "EN": "Trench & Duct Bank Design"},
    "p5_pad_title":  {"KO": "BESS 인클로저 & PCS 패드 규격 산정", "EN": "BESS Enclosure & PCS Pad Sizing"},
    "p5_inp_title":  {"KO": "#### 입력 파라미터",                "EN": "#### Input Parameters"},
    "p5_num_enc":    {"KO": "배터리 인클로저 수량",               "EN": "Number of Battery Enclosures"},
    "p5_soil":       {"KO": "지지력 (kPa)",                     "EN": "Soil Bearing Capacity (kPa)"},
    "p5_wind":       {"KO": "설계 풍속 (m/s)",                  "EN": "Design Wind Speed (m/s)"},
    "p5_enc_dim":    {"KO": "#### 인클로저 치수 (표준 20ft 환산)", "EN": "#### Enclosure Dimensions (Standard 20ft equiv)"},
    "p5_len":        {"KO": "길이 (m)",                         "EN": "Length (m)"},
    "p5_wid":        {"KO": "폭 (m)",                          "EN": "Width (m)"},
    "p5_wgt":        {"KO": "운전 중량 (ton)",                   "EN": "Operational Weight (tons)"},
    "p5_out_title":  {"KO": "#### 패드 설계 결과",               "EN": "#### Pad Design Outputs"},
    "p5_pad_l":      {"KO": "패드 길이 (m)",                    "EN": "Pad Length (m)"},
    "p5_pad_w":      {"KO": "패드 폭 (m)",                     "EN": "Pad Width (m)"},
    "p5_pad_a":      {"KO": "단위 패드 면적 (m²)",              "EN": "Single Pad Area (m²)"},
    "p5_tot_a":      {"KO": "총 패드 면적 (m²)",                "EN": "Total Pad Area (m²)"},
    "p5_brg":        {"KO": "하중/지지력 비율",                  "EN": "Load to Capacity Ratio"},
    "p5_brg_ok":     {"KO": "지지력 충족 — 표준 얕은기초 적용 가능.", "EN": "Soil bearing capacity OK — standard shallow foundation applicable."},
    "p5_brg_warn":   {"KO": "지지력 주의 — 심층 파일 또는 말뚝 기초 검토.",
                      "EN": "Marginal bearing — consider deep piles or mat foundation."},
    "p5_brg_err":    {"KO": "지지력 초과 — 특수 기초 설계 필요.",
                      "EN": "Bearing exceeded — special foundation design required."},
    "p5_trench_title":{"KO": "트렌치 & 덕트뱅크 설계",           "EN": "Trench & Duct Bank Design"},
    "p5_mv_n":       {"KO": "MV 케이블 총 수량",                "EN": "Total Number of MV Cables"},
    "p5_cable_od":   {"KO": "케이블 평균 외경 (mm)",             "EN": "Average Cable Outer Diameter (mm)"},
    "p5_spacing":    {"KO": "이격 배수 (1D, 2D)",               "EN": "Required Spacing Multiplier (1D, 2D)"},
    "p5_tw":         {"KO": "예상 트렌치 폭",                   "EN": "Estimated Trench Width"},
    "p5_td":         {"KO": "최소 트렌치 깊이",                  "EN": "Minimum Trench Depth"},
    "p5_trench_warn":{"KO": "트렌치 폭 과대. 다단 덕트뱅크 또는 병렬 트렌치 검토.",
                      "EN": "Trench width is substantial. Consider multi-layer duct banks or parallel trenches."},

    # ─── Data Analyst (06) ───────────────────────────────────────────
    "p6_caption":    {"KO": "🛤️ Step 5 (조달/토목) ➔ **[Step 6: 데이터 분석 & O&M]** ➔ 프로젝트 완료",
                      "EN": "🛤️ **BESS EPC Workflow:** Step 5 (Procurement/Civil) ➔ **[Step 6: Analytics & O&M]** ➔ Project Complete"},
    "p6_title":      {"KO": "📊 데이터 분석 툴킷",               "EN": "📊 Data Analyst Toolkit"},
    "p6_info":       {"KO": "BESS 성능 모니터링, 배터리 건전성 분석 및 이상 탐지 대시보드.",
                      "EN": "BESS Performance Monitoring, Battery Health Analytics, and Anomaly Detection dashboard."},
    "p6_tab1":       {"KO": "성능 지표",                        "EN": "Performance Metrics"},
    "p6_tab2":       {"KO": "배터리 건전성 (MoM)",               "EN": "Battery Health (MoM)"},
    "p6_tab3":       {"KO": "이상 탐지",                        "EN": "Anomaly Detection"},
    "p6_kpi":        {"KO": "BESS 운영 KPI 대시보드",            "EN": "BESS Operational KPI Dashboard"},
    "p6_avail":      {"KO": "시스템 가용률",                    "EN": "System Availability"},
    "p6_rte":        {"KO": "왕복 효율 (RTE)",                  "EN": "Round-Trip Efficiency"},
    "p6_disch":      {"KO": "일 평균 방전량",                   "EN": "Avg Daily Discharge"},
    "p6_aux":        {"KO": "보조 전력 사용",                   "EN": "Aux Power Usage"},
    "p6_monthly":    {"KO": "#### 월별 충·방전 프로파일 (MWh)", "EN": "#### Monthly Charge / Discharge Profile (MWh)"},
    "p6_soh_title":  {"KO": "배터리 SOH 추적 (State of Health)", "EN": "Battery State of Health (SOH) Tracking"},
    "p6_soh_desc":   {"KO": "등가 풀싸이클(EFC) 진행에 따른 용량 열화 추적.",
                      "EN": "Track capacity degradation over Equivalent Full Cycles (EFC)."},
    "p6_anomaly":    {"KO": "셀 불균형 & 이상 탐지",            "EN": "Cell Imbalance & Anomaly Detection"},
    "p6_hmap":       {"KO": "#### 랙 × 모듈 온도 히트맵 (°C)", "EN": "#### Rack vs Module Temperature Heatmap (°C)"},
    "p6_detect":     {"KO": "🔍 Isolation Forest 이상 탐지 실행", "EN": "🔍 Run Isolation Forest Anomaly Detection"},
    "p6_anomaly_err":{"KO": "⚠️ **이상 탐지!** R8, R9 랙 M3, M4 모듈에서 모듈 평균 대비 5σ 초과 온도 검출. 권고: HVAC 덕트 또는 셀 내부 저항 점검.",
                      "EN": "⚠️ **Anomaly Detected!** Rack R8, R9 on Modules M3, M4 exhibit temperatures > 5σ above module mean. Recommendation: Inspect HVAC ducting or cell internal resistance."},
    "p6_std_title":  {"KO": "🌐 지역별 데이터 보고 & 사이버보안 표준",
                      "EN": "🌐 Regional Data Reporting & Cybersecurity Standards"},

    # ─── IPO Checklists (07) ─────────────────────────────────────────
    "p7_caption":    {"KO": "🛤️ **BESS EPC 워크플로우:** [공통 기능: 전 단계 동적 I/P/O 체크리스트]",
                      "EN": "🛤️ **BESS EPC Workflow:** [Cross-functional Tool: Dynamic I/P/O Checklists for all phases]"},
    "p7_title":      {"KO": "📋 동적 I/P/O 플로우 체크리스트",   "EN": "📋 Dynamic I/P/O Flow Checklists"},
    "p7_info":       {"KO": "스킬 담당자를 선택하면 지식 베이스에서 해당 입력·프로세스·출력 가이드라인을 로드합니다.",
                      "EN": "Select a skill manager to load their specific Input, Process, and Output step-by-step guidelines directly from the knowledge base."},
    "p7_select":     {"KO": "BESS 에이전트 스킬 파일 선택",       "EN": "Select BESS Agent Skill File"},
    "p7_loaded":     {"KO": "### 로드된 프로파일:",              "EN": "### Loaded Profile:"},
    "p7_inp_hdr":    {"KO": "📥 [I] 입력 항목",                 "EN": "📥 [I] Inputs"},
    "p7_proc_hdr":   {"KO": "⚙️ [P] 프로세스",                 "EN": "⚙️ [P] Processes"},
    "p7_out_hdr":    {"KO": "📤 [O] 출력물",                   "EN": "📤 [O] Outputs"},
    "p7_inp_prog":   {"KO": "입력 검증: {c}/{t}",              "EN": "Inputs Verified: {c}/{t}"},
    "p7_proc_prog":  {"KO": "프로세스 완료: {c}/{t}",           "EN": "Processes Completed: {c}/{t}"},
    "p7_out_prog":   {"KO": "출력 생성: {c}/{t}",              "EN": "Outputs Generated: {c}/{t}"},
    "p7_sel_all_i":  {"KO": "☑️ 입력 전체 선택",               "EN": "☑️ Select All Inputs"},
    "p7_sel_all_p":  {"KO": "☑️ 프로세스 전체 선택",            "EN": "☑️ Select All Process"},
    "p7_sel_all_o":  {"KO": "☑️ 출력 전체 선택",               "EN": "☑️ Select All Outputs"},
    "p7_gateway":    {"KO": "자동 실행 & 승인 게이트웨이",        "EN": "Automated Execution & Approval Gateway"},
    "p7_warn_low":   {"KO": "⚠️ **검토 필요:** 에이전트 실행 전 더 많은 입력 항목 검증 및 초기 프로세스를 완료해 주세요.",
                      "EN": "⚠️ **Review Required:** Please verify more inputs and complete initial processes before triggering agents."},
    "p7_btn_agent":  {"KO": "🚀 선택된 작업에 AI 서브에이전트 실행", "EN": "🚀 Trigger AI Sub-Agents for Selected Tasks"},
    "p7_wip":        {"KO": "🔄 **작업 중:** AI 에이전트가 남은 프로세스를 지원할 준비가 되었습니다.",
                      "EN": "🔄 **Work in Progress:** AI Agents are ready to assist with the remaining processes."},
    "p7_done":       {"KO": "✅ **검증 완료:** 대부분의 작업이 완료되었습니다. 최종 엔지니어링 매니저 승인 준비 완료.",
                      "EN": "✅ **Validation Complete:** Most tasks are checked. Ready for final Engineering Manager approval."},
    "p7_approve":    {"KO": "✅ 단계 승인 & 최종 산출물 생성",     "EN": "✅ Approve Phase & Generate Final Deliverables"},
    "p7_compiling":  {"KO": "엔지니어링 아티팩트 컴파일 중...",   "EN": "Compiling Engineering Artifacts..."},
    "p7_finalizing": {"KO": "### 🗃️ 단계 산출물 최종화",         "EN": "### 🗃️ Finalizing Phase Deliverables"},
    "p7_approved":   {"KO": "🎉 **단계 공식 승인 완료!**",        "EN": "🎉 **Phase Officially Approved!**"},
    "p7_saved":      {"KO": "📁 **파일 저장 위치:**",             "EN": "📁 **File saved at:**"},
    "p7_dl_btn":     {"KO": "⬇️ 산출물 보고서 다운로드 (.txt)",   "EN": "⬇️ Download Deliverable Report (.txt)"},
    "p7_no_skill":   {"KO": "스킬 파일을 찾을 수 없습니다.",       "EN": "No markdown skills found."},
    "p7_agent_log":  {"KO": "### 📡 에이전트 커맨드 센터",         "EN": "### 📡 Agent Command Center"},
    "p7_dispatched": {"KO": "작업이 성공적으로 배포되었습니다!",   "EN": "Tasks Dispatched Successfully!"},
    "p7_running":    {"KO": "🤖 서브에이전트가 백그라운드에서 실행 중입니다. 초안이 준비되면 알림이 표시됩니다.",
                      "EN": "🤖 Sub-agents are now running in the background. You will be notified when drafts are ready for Output Review."},

    # ─ E-BOP extras (04) ─────────────────────────────────────────────
    "p4_base_mva":   {"KO": "기본 필요 MVA (보조부하 포함)",      "EN": "Base Required MVA (incl. Aux)"},
    "p4_target_mva": {"KO": "목표 MVA (설계여유 {margin}% 포함)", "EN": "Target MVA (w/ {margin}% Margin)"},
    "p4_aux_loss":   {"KO": "보조부하 손실 (%)",                   "EN": "Auxiliary Power Loss (%)"},
    "p2_epc_margin": {"KO": "설계 여유율 (%)",                    "EN": "Design Margin (%)"},

    # ─ C-BOP extras – HVAC + Fire (05) ───────────────────────────────
    "p5_tab3":        {"KO": "HVAC 냉방 부하 계산",               "EN": "HVAC Cooling Load"},
    "p5_tab4":        {"KO": "화재방호 설계",                     "EN": "Fire Suppression Design"},
    "p5_hvac_title":  {"KO": "배터리실 HVAC 냉방 부하 산정",      "EN": "Battery Room HVAC Cooling Load Calculation"},
    "p5_hvac_bat_heat":{"KO": "배터리 발열량 (kW)",              "EN": "Battery Heat Output (kW)"},
    "p5_hvac_pcs_heat":{"KO": "PCS/인버터 발열량 (kW)",          "EN": "PCS/Inverter Heat Output (kW)"},
    "p5_hvac_amb":    {"KO": "외기 설계 온도 (°C)",              "EN": "Outdoor Design Temp (°C)"},
    "p5_hvac_indoor": {"KO": "실내 설계 온도 (°C)",              "EN": "Indoor Design Temp (°C)"},
    "p5_hvac_safety": {"KO": "안전율 (%)",                       "EN": "Safety Factor (%)"},
    "p5_hvac_total":  {"KO": "총 냉방 부하 (kW)",                "EN": "Total Cooling Load (kW)"},
    "p5_hvac_units":  {"KO": "필요 HVAC 유닛 수",                "EN": "Required HVAC Units"},
    "p5_hvac_unit_kw":{"KO": "단위 HVAC 용량 (kW)",             "EN": "HVAC Unit Capacity (kW)"},
    "p5_hvac_power":  {"KO": "HVAC 소비 전력 (kW)",             "EN": "HVAC Power Consumption (kW)"},
    "p5_hvac_cop":    {"KO": "COP (에너지 효율 계수)",            "EN": "COP (Coefficient of Performance)"},
    "p5_hvac_ok":     {"KO": "✅ HVAC 용량 적정 — 냉방 부하 충족", "EN": "✅ HVAC capacity adequate"},
    "p5_hvac_warn":   {"KO": "⚠️ HVAC 용량 부족 — 증설 검토 필요", "EN": "⚠️ HVAC capacity marginal – review sizing"},
    "p5_fire_title":  {"KO": "화재 억제 시스템 설계 (FM-200 / Novec)", "EN": "Fire Suppression System Design (FM-200 / Novec)"},
    "p5_fire_room":   {"KO": "보호 구역",                        "EN": "Protected Space"},
    "p5_fire_vol":    {"KO": "보호 공간 체적 (m³)",              "EN": "Protected Volume (m³)"},
    "p5_fire_agent":  {"KO": "소화약제 종류",                    "EN": "Suppression Agent"},
    "p5_fire_conc":   {"KO": "설계 농도 (%)",                   "EN": "Design Concentration (%)"},
    "p5_fire_qty":    {"KO": "필요 약제량 (kg)",                 "EN": "Required Agent (kg)"},
    "p5_fire_cy":     {"KO": "실린더 수 (50 kg 기준)",           "EN": "Cylinders Required (50 kg each)"},
    "p5_fire_note":   {"KO": "⚠️ NFPA 2001 / ISO 14520 기준 간이식 적용", "EN": "⚠️ Simplified NFPA 2001 / ISO 14520 formula applied"},

    # ─ Container Thermal Simulation (09) ─────────────────────────────
    "p9_caption":     {"KO": "🔥 배터리 컨테이너 내부 열유동 시뮬레이션", "EN": "🔥 Battery Container Internal Thermal Flow Simulation"},
    "p9_title":       {"KO": "🌡️ 컨테이너 열유동 시뮬레이션",      "EN": "🌡️ Container Thermal Flow Simulation"},
    "p9_info":        {"KO": "배터리 발열량과 HVAC 냉방 용량을 입력하면 2D 열전도(FDM) 기반으로 컨테이너 내부 온도 분포를 시각화합니다.",
                      "EN": "Input battery heat and HVAC capacity to visualise internal temperature distribution via 2D Finite Difference Method (FDM)."},
    "p9_tab1":        {"KO": "🗺️ 바닥면 온도 분포",               "EN": "🗺️ Floor-Plan Temperature Map"},
    "p9_tab2":        {"KO": "📐 수직 단면 온도 분포",             "EN": "📐 Vertical Cross-Section"},
    "p9_tab3":        {"KO": "💨 공기 흐름 벡터장",               "EN": "💨 Airflow Vector Field"},
    "p9_params":      {"KO": "### ⚙️ 시뮬레이션 입력 파라미터",   "EN": "### ⚙️ Simulation Input Parameters"},
    "p9_amb":         {"KO": "외기 온도 (°C)",                   "EN": "Ambient Temperature (°C)"},
    "p9_bat_heat":    {"KO": "배터리 총 발열량 (kW)",             "EN": "Total Battery Heat Output (kW)"},
    "p9_hvac_cap":    {"KO": "HVAC 냉방 용량 (kW)",              "EN": "HVAC Capacity (kW)"},
    "p9_con_l":       {"KO": "컨테이너 길이 (m)",                 "EN": "Container Length (m)"},
    "p9_con_w":       {"KO": "컨테이너 폭 (m)",                  "EN": "Container Width (m)"},
    "p9_con_h":       {"KO": "컨테이너 높이 (m)",                 "EN": "Container Height (m)"},
    "p9_racks":       {"KO": "배터리 랙 수",                      "EN": "Number of Battery Racks"},
    "p9_run":         {"KO": "🚀 열유동 시뮬레이션 실행",          "EN": "🚀 Run Thermal Simulation"},
    "p9_max_temp":    {"KO": "최고 내부 온도",                    "EN": "Peak Internal Temp"},
    "p9_avg_temp":    {"KO": "평균 내부 온도",                    "EN": "Avg Internal Temp"},
    "p9_hotspot":     {"KO": "핫스팟 위치",                       "EN": "Hotspot Location"},
    "p9_hvac_ok":     {"KO": "✅ HVAC 용량 적정 — 최고온도 45°C 이하", "EN": "✅ HVAC adequate — peak below 45°C"},
    "p9_hvac_warn":   {"KO": "⚠️ 최고온도 45~55°C — HVAC 증설 권고", "EN": "⚠️ Peak 45–55°C — Increase HVAC capacity"},
    "p9_hvac_crit":   {"KO": "🚨 위험! 최고온도 55°C 초과 — 즉시 조치 필요", "EN": "🚨 Critical! Peak above 55°C — Immediate action required"},
    "p9_floor_title": {"KO": "컨테이너 바닥면 온도 분포 (°C)",    "EN": "Container Floor Temperature Distribution (°C)"},
    "p9_sec_title":   {"KO": "수직 단면 온도 분포 (°C)",          "EN": "Vertical Cross-Section Temperature (°C)"},
    "p9_air_title":   {"KO": "컨테이너 내부 공기 흐름 벡터장",    "EN": "Container Internal Airflow Vector Field"},
    "p9_x_label":     {"KO": "X 방향 (m)",                       "EN": "X Direction (m)"},
    "p9_y_label":     {"KO": "Y 방향 (m)",                       "EN": "Y Direction (m)"},
    "p9_z_label":     {"KO": "Z 높이 (m)",                       "EN": "Z Height (m)"},

    # ─ Fire Spread Simulation (10) ────────────────────────────────────
    "p10_caption":    {"KO": "🔥 배터리 화재 확산 시뮬레이션",    "EN": "🔥 Battery Fire Spread Simulation"},
    "p10_title":      {"KO": "🔥 화재 확산 모델 시뮬레이션",      "EN": "🔥 Fire Spread Model Simulation"},
    "p10_info":       {"KO": "배터리 열폭주(Thermal Runaway) 발생 시 컨테이너 내부 화재 확산 과정을 셀룰러 오토마타 기반으로 시뮬레이션합니다.",
                      "EN": "Simulates internal fire spread during Battery Thermal Runaway using a Cellular Automata model."},
    "p10_tab1":       {"KO": "🔥 확산 애니메이션",               "EN": "🔥 Spread Animation"},
    "p10_tab2":       {"KO": "📈 확산 면적 추이",                 "EN": "📈 Spread Area Over Time"},
    "p10_tab3":       {"KO": "⚖️ 방화 시스템 비교",             "EN": "⚖️ Suppression System Comparison"},
    "p10_params":     {"KO": "### ⚙️ 화재 시나리오 파라미터",    "EN": "### ⚙️ Fire Scenario Parameters"},
    "p10_chem":       {"KO": "배터리 화학종",                     "EN": "Battery Chemistry"},
    "p10_origin_r":   {"KO": "화재 발원 랙 행 (1~n)",             "EN": "Fire Origin Rack Row (1~n)"},
    "p10_origin_c":   {"KO": "화재 발원 랙 열 (1~n)",             "EN": "Fire Origin Rack Column (1~n)"},
    "p10_rows":       {"KO": "랙 행 수",                          "EN": "Rack Rows"},
    "p10_cols":       {"KO": "랙 열 수",                          "EN": "Rack Columns"},
    "p10_agent":      {"KO": "소화 시스템",                       "EN": "Suppression System"},
    "p10_response":   {"KO": "소화 시스템 반응 시간 (초)",         "EN": "Suppression Response Time (sec)"},
    "p10_run":        {"KO": "🚨 화재 확산 시뮬레이션 실행",      "EN": "🚨 Run Fire Spread Simulation"},
    "p10_total_t":    {"KO": "전체 진행 시간",                    "EN": "Total Simulation Time"},
    "p10_max_racks":  {"KO": "최대 확산 랙 수",                   "EN": "Max Racks Affected"},
    "p10_suppressed": {"KO": "소화 차단 랙 수",                   "EN": "Racks Suppressed"},
    "p10_anim_title": {"KO": "화재 확산 시뮬레이션 (시간 진행)", "EN": "Fire Spread Simulation (Time Progression)"},
    "p10_area_title": {"KO": "시간 경과별 화재 확산 랙 수",       "EN": "Fire Spread Area Over Time"},
    "p10_time_ax":    {"KO": "경과 시간 (초)",                   "EN": "Elapsed Time (sec)"},
    "p10_area_ax":    {"KO": "화재 영향 랙 수",                  "EN": "Racks on Fire"},
    "p10_cmp_title":  {"KO": "방화 시스템별 최대 확산 랙 수 비교", "EN": "Max Spread Comparison by Suppression System"},
    "p10_sys_ax":     {"KO": "소화 시스템",                      "EN": "Suppression System"},
    "p10_state0":     {"KO": "정상",     "EN": "Normal"},
    "p10_state1":     {"KO": "가열 중",  "EN": "Heating"},
    "p10_state2":     {"KO": "열폭주",   "EN": "Thermal Runaway"},
    "p10_state3":     {"KO": "화재",     "EN": "Fire"},
    "p10_state4":     {"KO": "소화됨",   "EN": "Suppressed"},

    # ─── Homepage / Dashboard (00) ────────────────────────────────────────
    "hp_sidebar_title":  {"KO": "BESS EPC 에이전트",           "EN": "BESS EPC Agent"},
    "hp_sidebar_ver":    {"KO": "**통합 대시보드 v1.0**",       "EN": "**Unified Dashboard v1.0**"},
    "hp_sidebar_hint":   {"KO": "위쪽 메뉴에서 각 담당 모듈을 선택하여 분야별 입력 항목, 파라미터 및 AI 출력 결과를 확인하세요.",
                          "EN": "Select a module from the menu above to view discipline-specific inputs, parameters, and AI-driven outputs."},
    "hp_page_title":     {"KO": "⚡ BESS EPC 통합 엔지니어링 플랫폼", "EN": "⚡ BESS EPC Unified Engineering Platform"},
    "hp_welcome":        {"KO": "**BESS EPC 통합 플랫폼**에 오신 것을 환영합니다. 이 대시보드는 AI 에이전트를 통해 BESS 프로젝트의 전체 수명주기에 걸쳐 엔지니어링 매니저를 지원합니다.",
                          "EN": "Welcome to the **BESS EPC Unified Platform**. This dashboard integrates AI Agents to assist engineering managers across all phases of the BESS lifecycle."},
    "hp_wf_title":       {"KO": "### 🛤️ BESS EPC 엔지니어링 워크플로우 가이드", "EN": "### 🛤️ BESS EPC Engineering Workflow Guide"},
    "hp_wf_sub":         {"KO": "아래 단계를 따라 BESS 전체 설계 사이클을 완료하세요.", "EN": "Follow the stages below to complete a full BESS design cycle."},
    "hp_progress":       {"KO": "전체 공정 진행률: {pct}% (현재 단계: {phase})",
                          "EN": "Overall Engineering Progress: {pct}% (Current Phase: {phase})"},
    "hp_phase_init":     {"KO": "프로젝트 초기 설정",            "EN": "Project Initial Setup"},
    "hp_phase_step1":    {"KO": "Step 1: 개념 & 범위 진행 중",    "EN": "Step 1: Concept & Scope in Progress"},
    "hp_phase_step2":    {"KO": "시스템 설계 & 분석",             "EN": "System Design & Analysis"},

    # Workflow step card titles & navigation labels
    "hp_w1_title":       {"KO": "**1. 개념 & 범위**",             "EN": "**1. Concept & Scope**"},
    "hp_w1_link":        {"KO": "📂 프로젝트 설정으로",            "EN": "📂 Project Setup"},
    "hp_w2_title":       {"KO": "**2. 시스템 설계**",             "EN": "**2. System Eng**"},
    "hp_w2_link":        {"KO": "📂 시스템 엔지니어링으로",         "EN": "📂 System Engineering"},
    "hp_w3_title":       {"KO": "**3. 3D & 해석**",               "EN": "**3. 3D & Analysis**"},
    "hp_w3_link":        {"KO": "📂 3D 시뮬레이션으로",            "EN": "📂 3D Simulation"},
    "hp_w4_title":       {"KO": "**4. E-BOP 설계**",              "EN": "**4. E-BOP Design**"},
    "hp_w4_link":        {"KO": "📂 E-BOP 엔지니어로",             "EN": "📂 E-BOP Engineer"},
    "hp_w5_title":       {"KO": "**5. 토목 & C-BOP**",            "EN": "**5. Civil & C-BOP**"},
    "hp_w5_link":        {"KO": "📂 C-BOP 엔지니어로",             "EN": "📂 C-BOP Engineer"},
    "hp_w6_title":       {"KO": "**6. 데이터 분석 & O&M**",       "EN": "**6. Analytics & O&M**"},
    "hp_w6_link":        {"KO": "📂 데이터 분석으로",              "EN": "📂 Data Analyst"},

    # Workflow item labels (bilingual; status icon is prepended in Python)
    "hp_wi_sizing":      {"KO": "기본 용량 산정",  "EN": "Basic Sizing"},
    "hp_wi_rfp":         {"KO": "RFP 검토",        "EN": "RFP Review"},
    "hp_wi_feasib":      {"KO": "타당성 분석",     "EN": "Feasibility"},
    "hp_wi_arch":        {"KO": "시스템 아키텍처", "EN": "Architecture"},
    "hp_wi_sld":         {"KO": "SLD 초안",        "EN": "SLD Draft"},
    "hp_wi_pcs":         {"KO": "PCS 선정",        "EN": "PCS Selection"},
    "hp_wi_cfd":         {"KO": "열유동 CFD",      "EN": "Thermal CFD"},
    "hp_wi_struct":      {"KO": "구조 해석",       "EN": "Structural"},
    "hp_wi_fds":         {"KO": "화재/FDS",         "EN": "Fire/FDS"},
    "hp_wi_tr":          {"KO": "TR 용량 산정",    "EN": "TR Sizing"},
    "hp_wi_cable":       {"KO": "케이블 설계",     "EN": "Cable Sizing"},
    "hp_wi_gnd":         {"KO": "접지 설계",       "EN": "Grounding"},
    "hp_wi_pad":         {"KO": "패드 설계",       "EN": "Pad Design"},
    "hp_wi_hvac":        {"KO": "HVAC 사양",       "EN": "HVAC Spec"},
    "hp_wi_fire_prot":   {"KO": "화재 방호",       "EN": "Fire Protection"},
    "hp_wi_kpi":         {"KO": "KPI 설정",        "EN": "KPI Setup"},
    "hp_wi_deg":         {"KO": "열화 분석",       "EN": "Degradation"},

    # KPI metric labels
    "hp_m1":             {"KO": "진행 중 프로젝트", "EN": "Active Projects"},
    "hp_m2":             {"KO": "누적 시뮬레이션",  "EN": "Simulations Ran"},
    "hp_m3":             {"KO": "공정 완료율",      "EN": "Workflow Completion"},
    "hp_m4":             {"KO": "결재 대기",        "EN": "Pending Approvals"},
    "hp_m2_delta":       {"KO": "이번 주 12회",     "EN": "12 This Week"},

    # System architecture overview
    "hp_arch_title":     {"KO": "시스템 아키텍처 개요", "EN": "System Architecture Overview"},
    "hp_arch_info":      {"KO": "AI 에이전트가 입력 변수를 지속적으로 모니터링 중입니다. 세부 액션 아이템은 각 담당 스킬 모듈을 참조하세요.",
                          "EN": "AI Agents are continuously monitoring input variables. Please refer to specific skill modules for detailed action items."},
    "hp_chart_title":    {"KO": "현재 프로젝트 단계별 진행률", "EN": "Current Project Phase Progress"},
    "hp_chart_x":        {"KO": "단계",              "EN": "Phase"},
    "hp_chart_y":        {"KO": "진행률 (%)",        "EN": "Progress (%)"},
    "hp_phase_design":   {"KO": "설계",              "EN": "Design"},
    "hp_phase_proc":     {"KO": "조달",              "EN": "Procurement"},
    "hp_phase_const":    {"KO": "시공",              "EN": "Construction"},
    "hp_phase_comm":     {"KO": "시운전",            "EN": "Commissioning"},

    # Additional engineering tools section (pages 07–10)
    "hp_tools_title":    {"KO": "### 🔧 추가 엔지니어링 도구",  "EN": "### 🔧 Additional Engineering Tools"},
    "hp_tools_sub":      {"KO": "메인 워크플로우와 독립적으로 사용 가능한 전문 도구들입니다.",
                          "EN": "Specialized tools that can be used independently of the main workflow."},
    "hp_ipo_title":      {"KO": "📋 I/P/O 체크리스트",          "EN": "📋 IPO Checklists"},
    "hp_ipo_desc":       {"KO": "전 단계 동적 입력·프로세스·출력 체크리스트",
                          "EN": "Dynamic Input / Process / Output checklists for all phases"},
    "hp_ipo_link":       {"KO": "📂 IPO 체크리스트로",           "EN": "📂 IPO Checklists"},
    "hp_launcher_title": {"KO": "🚀 도구 런처",                  "EN": "🚀 Tool Launcher"},
    "hp_launcher_desc":  {"KO": "40+ BESS EPC 독립 실행형 도구 관리 및 실행",
                          "EN": "Launch & manage 40+ standalone BESS EPC tools"},
    "hp_launcher_link":  {"KO": "📂 도구 런처로",               "EN": "📂 Tool Launcher"},
    "hp_thermal_title":  {"KO": "🌡️ 컨테이너 열유동",           "EN": "🌡️ Container Thermal"},
    "hp_thermal_desc":   {"KO": "2D FDM 기반 배터리 컨테이너 내부 온도 시뮬레이션",
                          "EN": "2D FDM battery container internal temperature simulation"},
    "hp_thermal_link":   {"KO": "📂 컨테이너 열유동으로",        "EN": "📂 Container Thermal"},
    "hp_fire_title":     {"KO": "🔥 화재 확산 시뮬레이션",       "EN": "🔥 Fire Spread Simulation"},
    "hp_fire_desc":      {"KO": "셀룰러 오토마타 기반 열폭주 화재 확산 모델",
                          "EN": "Cellular automata-based thermal runaway fire spread model"},
    "hp_fire_link":      {"KO": "📂 화재 확산 시뮬레이션으로",   "EN": "📂 Fire Spread Simulation"},
    "hp_cyber_title":    {"KO": "🔐 사이버보안 & 시스템 검토",   "EN": "🔐 Cybersecurity & System Review"},
    "hp_cyber_desc":     {"KO": "IEC 62443 · NERC CIP · 네트워크 보안 · 접근 제어 체크리스트",
                          "EN": "IEC 62443 · NERC CIP · Network Security · Access Control checklists"},
    "hp_cyber_link":     {"KO": "📂 사이버보안 체크리스트로",     "EN": "📂 Cybersecurity Checklist"},

}


def t(key: str, **kwargs) -> str:
    """Return the translated string for the current session language.
    Optional kwargs are used for .format(**kwargs) substitution.
    """
    lang = st.session_state.get("lang", "KO")
    entry = _TRANSLATIONS.get(key, {})
    text = entry.get(lang, entry.get("EN", key))
    if kwargs:
        try:
            text = text.format(**kwargs)
        except (KeyError, ValueError):
            pass
    return text
